contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1dee7e9b-c6b0-4425-8429-65e33f1a1596
inputs: []
name: new-playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ef0955f8-946f-4866-83d3-49143775f620
      iscommand: false
      name: ""
      version: -1
    taskid: ef0955f8-946f-4866-83d3-49143775f620
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5d0cf74e-57f7-44a0-8809-5046dc69a798
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 5d0cf74e-57f7-44a0-8809-5046dc69a798
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 420,
          "y": 320
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 365,
        "width": 410,
        "x": 420,
        "y": 50
      }
    }
  }
