contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: Deprecated. Use the Dedup Generic v3 playbook instead. This playbook
  identifies duplicate incidents using one of the supported methods.
hidden: true
id: Dedup - Generic v2
inputs:
- description: Select a method for identifying duplicate incidents. Can be "ml", "rules",
    or "text". 'rules' - defines specific rules, such as similar incident fields &
    labels. This method works best if you know the exact logic to find similar incidents.
    'text' - text similarity, based on TF-IDF - unique word frequency in the incidents
    (based on similar incident fields) 'ml' - machine learning model, which was trained
    on similar phishing incidents. Considers similar labels, incident fields, and
    indicators.
  key: DuplicateMethod
  playbookInputQuery: null
  required: true
  value: {}
- description: The similarity threshold by which to consider an incident as a duplicate
    (0-1), where "1" is a duplicate and "0" is not a duplicate. Use this argument
    in the ML or text methods.
  key: DuplicateThreshold
  playbookInputQuery: null
  required: true
  value:
    simple: "0.9"
- description: The time frame (in hours) in which to check for duplicate incident
    candidates.
  key: TimeFrameHours
  playbookInputQuery: null
  required: true
  value:
    simple: "72"
- description: Whether to ignore closed incidents. Can be "yes" or "no".
  key: IgnoreCloseIncidents
  playbookInputQuery: null
  required: true
  value:
    simple: "yes"
- description: The maximum number of candidates to check for duplication.
  key: MaxNumberOfCandidates
  playbookInputQuery: null
  required: false
  value:
    simple: "1000"
- description: Whether to close incidents identified as duplicates. Can be "true"
    or "false".
  key: CloseAsDuplicate
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
- description: 'The Time field by which to query for past incidents to check for duplicate
    incident candidates. Values: created, occurred, modified'
  key: TimeField
  playbookInputQuery: null
  required: false
  value:
    simple: created
- description: 'A comma-separated list of similar label keys. Comma separated value.
    Also supports allowing X different words between labels, within the following
    way: label_name:X, where X is the number of words. X can also be ''*'' for contains.
    For example: the value "Email/subject:*" will consider email subject similar,
    if one is substring of the other. Relevant for ''Rules'' method.'
  key: similarLabelsKeys
  playbookInputQuery: null
  required: false
  value: {}
- description: Fields to compare. Can be label name, incident fields or custom fields.
    Comma separated value. Relevant for 'Text' and 'Rules' methods.
  key: similarIncidentFields
  playbookInputQuery: null
  required: false
  value:
    simple: name,type,details
name: Dedup - Generic v2
outputs:
- contextPath: isSimilarIncidentFound
  description: Whether a similar incident was found? Can be "true" or "false".
  type: boolean
- contextPath: similarIncident
  description: The similar incident.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4bb4cba3-1da4-4356-831e-87ca6523087a
      iscommand: false
      name: ""
      version: -1
    taskid: 4bb4cba3-1da4-4356-831e-87ca6523087a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": -40
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.DuplicateMethod
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: ml
      label: ml
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.DuplicateMethod
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: rules
      label: rules
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.DuplicateMethod
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: text
      label: text
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      ml:
      - "11"
      rules:
      - "12"
      text:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Select one of the following methods to identify duplicate incidents in Cortex XSOAR.
        - ml: Machine learning model, which is trained mostly on phishing incidents.
        -rules: Rules help identify duplicate incidents when the logic is well defined, for example, same label or custom fields.
        -text: Statistics algorithm that compares text, which is generally useful for phishing incidents.
      id: 48f0cedf-fad2-47db-81fd-348b062f41fe
      iscommand: false
      name: Select method to identify duplicates
      type: condition
      version: -1
    taskid: 48f0cedf-fad2-47db-81fd-348b062f41fe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 105
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ignoreClosedIncidents:
        simple: ${inputs.IgnoreCloseIncidents}
      maximumNumberOfIncidents:
        complex:
          root: inputs.MaxNumberOfCandidates
      textFields:
        complex:
          root: inputs.similarIncidentFields
      threshold:
        complex:
          root: inputs.DuplicateThreshold
      timeField:
        simple: ${inputs.TimeField}
      timeFrameHours:
        complex:
          root: inputs.TimeFrameHours
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 14149636-c0cc-41de-88dd-4b91a49b87ce
      iscommand: false
      name: Identify duplicates by text
      script: FindSimilarIncidentsByText
      type: regular
      version: -1
    taskid: 14149636-c0cc-41de-88dd-4b91a49b87ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": 485
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if any duplicate incidents were found.
      id: b6bd2e9d-c6ca-401c-87f5-7dd2b6355bb3
      iscommand: false
      name: Check if duplicates were found
      type: condition
      version: -1
    taskid: b6bd2e9d-c6ca-401c-87f5-7dd2b6355bb3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 660
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      hoursBack:
        complex:
          root: inputs.TimeFrameHours
      ignoreClosedIncidents:
        simple: ${inputs.IgnoreCloseIncidents}
      maxNumberOfIncidents:
        complex:
          root: inputs.MaxNumberOfCandidates
      similarIncidentFields:
        complex:
          root: inputs.similarIncidentFields
      similarLabelsKeys:
        complex:
          root: inputs.similarLabelsKeys
      timeField:
        simple: ${inputs.TimeField}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Finds similar incidents by common incident keys, labels, custom fields or context keys.
        It's highly recommended to use incident keys if possible (e.g., "type" for the same incident type).
        For best performance, it's recommended to avoid using context keys if possible (for example, if the value also appears in a label key, use the label).
      id: c5bb7095-cdc3-4a83-8ae4-ed792366f468
      iscommand: false
      name: Identify similar incidents using rules
      script: FindSimilarIncidents
      type: regular
      version: -1
    taskid: c5bb7095-cdc3-4a83-8ae4-ed792366f468
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 485
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ignoreClosedIncidents:
        simple: ${inputs.IgnoreCloseIncidents}
      maxNumberOfIncidents:
        complex:
          root: inputs.MaxNumberOfCandidates
      threshold:
        complex:
          root: inputs.DuplicateThreshold
      timeField:
        simple: ${inputs.TimeField}
      timeFrameHours:
        complex:
          root: inputs.TimeFrameHours
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8cbb827c-a410-4f16-8a98-41026ce58f81
      iscommand: false
      name: Identify duplicates using ML
      script: GetDuplicatesMlv2
      type: regular
      version: -1
    taskid: 8cbb827c-a410-4f16-8a98-41026ce58f81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 485
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      duplicateId:
        complex:
          accessor: rawId
          root: similarIncident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Closes the investigation as a duplicate to one of the incidents
        identified.
      id: 821fea71-8442-4647-8281-52c916a04b43
      iscommand: false
      name: Close investigation as duplicate
      script: CloseInvestigationAsDuplicate
      type: regular
      version: -1
    taskid: 821fea71-8442-4647-8281-52c916a04b43
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1200,
          "y": 1000
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c1f06a79-d539-4853-8140-f1f879a8f137
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c1f06a79-d539-4853-8140-f1f879a8f137
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1460
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 31571cc9-8aed-458c-8ea2-f1cb69acb262
      iscommand: false
      name: Text
      type: title
      version: -1
    taskid: 31571cc9-8aed-458c-8ea2-f1cb69acb262
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 10,
          "y": 340
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4072604a-379d-4c5b-8e9f-b74b0e4d0184
      iscommand: false
      name: ML
      type: title
      version: -1
    taskid: 4072604a-379d-4c5b-8e9f-b74b0e4d0184
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 950,
          "y": 340
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 58c2edb1-ada1-4220-844d-805f1da22ae9
      iscommand: false
      name: Rules
      type: title
      version: -1
    taskid: 58c2edb1-ada1-4220-844d-805f1da22ae9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.CloseAsDuplicate
                transformers:
                - operator: toLowerCase
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0eaa279f-7d04-469d-8bcd-0ca1f7942c88
      iscommand: false
      name: Close duplicates?
      type: condition
      version: -1
    taskid: 0eaa279f-7d04-469d-8bcd-0ca1f7942c88
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 970,
          "y": 830
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      linkedIncidentIDs:
        complex:
          accessor: rawId
          root: similarIncident
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Links similar incidents.
      id: 2f6d5087-c0f1-47e3-8065-06cc25ced46a
      iscommand: true
      name: Link similar incidents
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: 2f6d5087-c0f1-47e3-8065-06cc25ced46a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": 1180
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Demisto REST API
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the Demisto REST API integration is enabled.
      id: 04d3848d-57da-47ab-827d-8950c9063c32
      iscommand: false
      name: Is Demisto REST API enabled?
      type: condition
      version: -1
    taskid: 04d3848d-57da-47ab-827d-8950c9063c32
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 750,
          "y": 1000
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_9_#default#": 0.32,
      "5_9_#default#": 0.28
    },
    "paper": {
      "dimensions": {
        "height": 1565,
        "width": 1570,
        "x": 10,
        "y": -40
      }
    }
  }
