contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5e25c0fe-599f-4492-867e-4757df1e3d3d
inputs: []
name: ggg
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 282599a8-2ad2-4a1f-8746-40a25f3929e5
      iscommand: false
      name: ""
      version: -1
    taskid: 282599a8-2ad2-4a1f-8746-40a25f3929e5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 00628804-d5c2-4477-8bac-dd39263af41c
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 00628804-d5c2-4477-8bac-dd39263af41c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 280
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 325,
        "width": 400,
        "x": 450,
        "y": 50
      }
    }
  }
