contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 2.1.39
    packID: Palo_Alto_Networks_WildFire
    packName: WildFire by Palo Alto Networks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  Detonate one or more files using the Wildfire v2 integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
  The detonation supports the following file types -
  APK, JAR, DOC, DOCX, RTF, XLS, XLSX, PPT, PPTX, XML, PE32, PDF, DMG, PKG, RAR, 7Z.
id: Detonate File From URL - WildFire v2
inputs:
- description: URL of the web file to detonate. The FileUrl is taken from the context.
  key: FileURL
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: FileURL
      transformers:
      - operator: uniq
- description: Duration for executing the pooling (in minutes).
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: The duration after which to stop pooling and to resume the playbook
    (in minutes).
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "8"
- description: The resource type to download. Default is pdf. XML is also possible.
  key: ReportFileType
  playbookInputQuery: null
  required: false
  value: {}
name: Detonate File From URL - WildFire v2
outputs:
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
- contextPath: File.Size
  description: File size.
  type: number
- contextPath: File.MD5
  description: MD5 hash of the file.
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file.
  type: string
- contextPath: File.Type
  description: File type, e.g., "PE".
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file.
  type: string
- contextPath: File.EntryID
  description: The Entry ID of the sample.
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision.
  type: string
- contextPath: File.Name
  description: Filename.
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason the vendor made the decision.
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator tested.
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator.
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score.
  type: string
- contextPath: IP.Address
  description: IPs relevant to the sample.
  type: string
- contextPath: File
  description: The file object.
  type: unknown
- contextPath: InfoFile
  description: The report file object.
  type: unknown
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file.
  type: string
- contextPath: InfoFile.Extension
  description: The extension of the report file.
  type: string
- contextPath: InfoFile.Name
  description: The name of the report file.
  type: string
- contextPath: InfoFile.Info
  description: The info of the report file.
  type: string
- contextPath: InfoFile.Size
  description: The size of the report file.
  type: number
- contextPath: InfoFile.Type
  description: The type of the report file.
  type: string
- contextPath: File.Malicious
  description: The malicious object.
  type: unknown
- contextPath: WildFire.Report
  description: The submission object.
  type: unknown
- contextPath: WildFire.Report.MD5
  description: MD5 of the submission.
  type: string
- contextPath: WildFire.Report.SHA256
  description: SHA256 of the submission.
  type: string
- contextPath: WildFire.Report.FileType
  description: The type of the submission.
  type: string
- contextPath: WildFire.Report.Status
  description: The status of the submission.
  type: string
- contextPath: WildFire.Report.Size
  description: The size of the submission.
  type: number
- contextPath: WildFire.Report.ExtractedURL.URL
  description: The extracted URL.
  type: string
- contextPath: WildFire.Report.ExtractedURL.Verdict
  description: The extracted verdict.
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 219dcb92-ee7d-420e-816e-3f70b24bd953
      iscommand: false
      name: ""
      version: -1
    taskid: 219dcb92-ee7d-420e-816e-3f70b24bd953
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 11650265-0035-421f-8e92-143af887b7a7
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 11650265-0035-421f-8e92-143af887b7a7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -60,
          "y": 910
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.FileURL
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Look for file URLs to detonate
      id: 4a6315f7-7947-4cfc-8554-4e6b3edb4478
      iscommand: false
      name: Is there a File to detonate?
      type: condition
      version: -1
    taskid: 4a6315f7-7947-4cfc-8554-4e6b3edb4478
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 280,
          "y": 380
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: WildFire-v2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if integration instance is enabled.
      id: efcfaf80-ceaa-4a4e-8534-c8b9d905db8b
      iscommand: false
      name: Is WildFire sandbox enabled?
      type: condition
      version: -1
    taskid: efcfaf80-ceaa-4a4e-8534-c8b9d905db8b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      format:
        complex:
          root: inputs.ReportFileType
      sha256:
        complex:
          accessor: SHA256
          root: WildFire.Report
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve results for a file hash using WildFire.
      id: e308b16b-fa8f-4898-8d17-228ea6638a33
      iscommand: true
      name: WildFire Get Report
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: e308b16b-fa8f-4898-8d17-228ea6638a33
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 740
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      interval_in_seconds:
        complex:
          root: inputs.Interval
      polling:
        simple: "true"
      timeout_in_seconds:
        complex:
          root: inputs.Timeout
      upload:
        complex:
          root: inputs.FileURL
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uploads the URL of a remote file to WildFire for analysis.
      id: f70f9254-9f72-4947-8e9b-75836952ab68
      iscommand: true
      name: WildFire Upload File URL
      script: '|||wildfire-upload-file-url'
      type: regular
      version: -1
    taskid: f70f9254-9f72-4947-8e9b-75836952ab68
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 925,
        "width": 920,
        "x": -60,
        "y": 50
      }
    }
  }
