contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.5.2
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: Deprecated. Use `Search And Delete Emails - Generic v2` instead. This
  playbook searches and delete emails with similar attributes of a malicious email.
id: search_and_delete_emails_-_generic
inputs:
- description: The value of the malicious email's "From" attribute.
  key: From
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: emailfrom
      root: incident
- description: The value of the malicious email's "Subject" attribute.
  key: Subject
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: emailsubject
      root: incident
- description: The value of the malicious email's "AttachmentName" attribute.
  key: AttachmentName
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: attachmentname
      root: incident
name: Search And Delete Emails - Generic
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 808e9cce-8112-49d4-8624-907a6fbeb394
      iscommand: false
      name: ""
      version: -1
    taskid: 808e9cce-8112-49d4-8624-907a6fbeb394
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      AttachmentName:
        complex:
          root: inputs.AttachmentName
      DeleteType:
        simple: trash
      From:
        complex:
          root: inputs.From
      Limit:
        simple: "20"
      SearchThisWeek:
        simple: "true"
      Subject:
        complex:
          root: inputs.Subject
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook searches EWS to identify and delete emails with similar
        attributes of a malicious email.
      id: 2c636e7e-8de1-4535-8c36-454b2c36cc75
      iscommand: false
      name: Search And Delete Emails - EWS
      playbookName: Search And Delete Emails - EWS
      type: playbook
      version: -1
    taskid: 2c636e7e-8de1-4535-8c36-454b2c36cc75
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 88c58e53-8fe7-4ca2-8697-0ed3f67191fe
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 88c58e53-8fe7-4ca2-8697-0ed3f67191fe
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
