contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "This playbook uses the generic command !endpoint to retrieve details
  on a specific endpoint.\nThis command currently supports the following integrations:\n-
  Palo Alto Networks Cortex XDR - Investigation and Response.\n- CrowdStrike Falcon. "
id: Get endpoint details - Generic
inputs:
- description: 'The ID of the endpoint that you want to get details about. '
  key: Endpoint_id
  playbookInputQuery: null
  required: false
  value: {}
- description: 'The IP of the endpoint that you want to get details about. '
  key: Endpoint_ip
  playbookInputQuery: null
  required: false
  value: {}
- description: 'The hostname of the endpoint that you want to get details about. '
  key: Endpoint_hostname
  playbookInputQuery: null
  required: false
  value: {}
name: Get endpoint details - Generic
outputs:
- contextPath: Endpoint.Hostname
  description: The endpoint's hostname.
  type: string
- contextPath: Endpoint.OS
  description: The endpoint's operation system.
  type: string
- contextPath: Endpoint.IPAddress
  description: The endpoint's IP address.
  type: string
- contextPath: Endpoint.ID
  description: The endpoint's ID.
  type: string
- contextPath: Endpoint.Status
  description: The endpoint's status.
  type: string
- contextPath: Endpoint.IsIsolated
  description: Endpoint isolation status.
  type: string
- contextPath: Endpoint.MACAddress
  description: Endpoint MAC address.
  type: string
- contextPath: Endpoint.Vendor
  description: The integration name of the endpoint vendor.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9716b204-62a4-450c-8253-26271fde0c01
      iscommand: false
      name: ""
      version: -1
    taskid: 9716b204-62a4-450c-8253-26271fde0c01
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Endpoint_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 54bb9713-a67d-4c97-8422-65d5c9ae1b88
      iscommand: false
      name: Is the endpoint id was provided?
      type: condition
      version: -1
    taskid: 54bb9713-a67d-4c97-8422-65d5c9ae1b88
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${inputs.Endpoint_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns information about an endpoint.
      id: 7ad4b670-6c2b-47f3-8475-0cff052ec80c
      iscommand: true
      name: Get endpoint by ID
      script: '|||endpoint'
      type: regular
      version: -1
    taskid: 7ad4b670-6c2b-47f3-8475-0cff052ec80c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 550
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Endpoint_hostname
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55202260-763a-4ab5-854b-e3d732645504
      iscommand: false
      name: Is the hostname provided?
      type: condition
      version: -1
    taskid: 55202260-763a-4ab5-854b-e3d732645504
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 570
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        simple: ${inputs.Endpoint_hostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns information about an endpoint.
      id: 9b85faf0-0d1f-41cc-858c-47a1011746cd
      iscommand: true
      name: Get endpoint by hostname
      script: '|||endpoint'
      type: regular
      version: -1
    taskid: 9b85faf0-0d1f-41cc-858c-47a1011746cd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 780
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1eed6e13-e39f-45f2-86f0-021a16a24a66
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1eed6e13-e39f-45f2-86f0-021a16a24a66
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2040
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Endpoint_ip
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d118de51-1c82-4f69-8454-61f80edd0741
      iscommand: false
      name: Is the endpoint IP provided?
      type: condition
      version: -1
    taskid: d118de51-1c82-4f69-8454-61f80edd0741
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 2840,
          "y": 770
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${inputs.Endpoint_ip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns information about an endpoint.
      id: 3fdf2df6-ea67-4639-8ef1-2f32d783f32e
      iscommand: true
      name: Get endpoint by IP
      script: '|||endpoint'
      type: regular
      version: -1
    taskid: 3fdf2df6-ea67-4639-8ef1-2f32d783f32e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 3110,
          "y": 1005
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Endpoint.ID}
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e2f57f23-a132-41f2-8ceb-3a84c652333b
      iscommand: false
      name: Is the endpoint details retrieved by ID?
      type: condition
      version: -1
    taskid: e2f57f23-a132-41f2-8ceb-3a84c652333b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Endpoint_id
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 21ed3ecb-a998-4ef0-8864-3dbd44e89a89
      iscommand: false
      name: Is agent ID provided?
      type: condition
      version: -1
    taskid: 21ed3ecb-a998-4ef0-8864-3dbd44e89a89
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 790,
          "y": 980
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint.ID
      value:
        simple: ${inputs.Endpoint_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 90239616-0624-4464-8b2b-ff9b92ab5069
      iscommand: false
      name: Set endpoint ID to context
      script: Set
      type: regular
      version: -1
    taskid: 90239616-0624-4464-8b2b-ff9b92ab5069
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 1160
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Endpoint.Hostname}
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f40bcf3f-0570-41e3-8c97-fe26908b3a13
      iscommand: false
      name: 'Is the endpoint details retrieved by hostname? '
      type: condition
      version: -1
    taskid: f40bcf3f-0570-41e3-8c97-fe26908b3a13
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1710,
          "y": 980
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Endpoint_hostname
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 645a04bf-3e22-407e-873d-f571a05b5225
      iscommand: false
      name: Was hostname provided?
      type: condition
      version: -1
    taskid: 645a04bf-3e22-407e-873d-f571a05b5225
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1820,
          "y": 1210
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Endpoint.Hostname
      value:
        simple: ${inputs.Endpoint_hostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: eecde4bf-341f-4347-8192-c9067f63727e
      iscommand: false
      name: Set endpoint hostname to context
      script: Set
      type: regular
      version: -1
    taskid: eecde4bf-341f-4347-8192-c9067f63727e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1950,
          "y": 1450
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Endpoint.IPAddress}
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6f50e01-1671-422d-8a29-90c685e03e48
      iscommand: false
      name: Is the endpoint details retrieved by IP?
      type: condition
      version: -1
    taskid: c6f50e01-1671-422d-8a29-90c685e03e48
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 3110,
          "y": 1210
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Endpoint.IPAddress
      value:
        simple: ${inputs.Endpoint_ip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: e40edb78-b5f5-4b04-82e5-92693f2e7bfc
      iscommand: false
      name: Set endpoint IP to context
      script: Set
      type: regular
      version: -1
    taskid: e40edb78-b5f5-4b04-82e5-92693f2e7bfc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 3870,
          "y": 1650
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Endpoint_ip
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3ab69c5f-8c2b-4ef7-81a1-6fafd368c9ec
      iscommand: false
      name: Was endpoint IP provided?
      type: condition
      version: -1
    taskid: 3ab69c5f-8c2b-4ef7-81a1-6fafd368c9ec
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 3370,
          "y": 1410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "11_5_yes": 0.22,
      "12_5_#default#": 0.17,
      "14_5_yes": 0.2,
      "17_5_#default#": 0.1,
      "1_2_yes": 0.52,
      "1_3_#default#": 0.51,
      "3_4_yes": 0.46,
      "3_6_#default#": 0.5,
      "6_7_yes": 0.46,
      "9_5_#default#": 0.26
    },
    "paper": {
      "dimensions": {
        "height": 1975,
        "width": 3800,
        "x": 450,
        "y": 130
      }
    }
  }
