contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.1.22
    packID: TIM_Processing
    packName: TIM - Indicator Auto-Processing
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbooks allows you to exclude indicators according to the number
  of incidents the indicator is related to. The indicator query is "investigationsCount:>=X"
  where X is the number of related incidents to the indicator that you set. Excluded
  indicators are located in the Cortex XSOAR exclusion list and are removed from all
  of their related incidents and future ones. The purpose of excluding these indicators
  is to reduce the amount internal and common indicators appearing in many incidents
  and showing only relevant indicators. Creating exclusions can also accelerate performance.
id: TIM - Indicators Exclusion By Related Incidents
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
- description: |-
    This input specifies which action the playbook performs on the provided indicators. Possible input values can be
        AutoExclude
        TagIndicators
  key: ActionToPerform
  playbookInputQuery: null
  required: false
  value: {}
- description: This input specifies the tag value to apply to the indicators. An example
    value can be whitelist_review. This input should be used only if The ActionToPerform
    input value is TagIndicators.
  key: TagValueForIndicators
  playbookInputQuery: null
  required: false
  value: {}
- description: This input determines if processed indicators that have the whitelist
    review tag are reviewed in a new incident. To create an incident, enter any value
    other than 'No'.
  key: OpenIncidentToReviewIndicatorsManually
  playbookInputQuery: null
  required: false
  value:
    simple: "No"
- description: Provide the reason that will appear in the XSOAR exclusion
  key: AutoExcludeReason
  playbookInputQuery: null
  required: false
  value: {}
name: TIM - Indicators Exclusion By Related Incidents
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 73c05597-8f99-4aad-89bb-b7b7eefb9c0a
      iscommand: false
      name: ""
      version: -1
    taskid: 73c05597-8f99-4aad-89bb-b7b7eefb9c0a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 90
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ActionToPerform
          operator: isEqualString
          right:
            value:
              simple: AutoExclude
      label: Auto exclude
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.ActionToPerform
          operator: isEqualString
          right:
            value:
              simple: TagIndicators
      - - left:
            iscontext: true
            value:
              simple: inputs.TagValueForIndicators
          operator: isNotEmpty
      label: Create manual incident
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      Auto exclude:
      - "9"
      Create manual incident:
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4525954c-5152-4069-864f-2ef2092cb066
      iscommand: false
      name: Was a valid input provided?
      type: condition
      version: -1
    taskid: 4525954c-5152-4069-864f-2ef2092cb066
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100,
          "y": 400
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eeb4f997-fec3-4236-8b11-823b9f2cb9ae
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: eeb4f997-fec3-4236-8b11-823b9f2cb9ae
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1100
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.value
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1d5b7b59-b477-4b17-82e8-8bb770180f4f
      iscommand: false
      name: Are there query results?
      type: condition
      version: -1
    taskid: 1d5b7b59-b477-4b17-82e8-8bb770180f4f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: Review Indicators Manually For Whitelisting
      type:
        simple: Review Indicators Manually For Whitelisting
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Create a new incident to manually review indicators for exclusion.
      id: 3b2faf00-1df0-4dfd-8fc8-a7585ba16d97
      iscommand: true
      name: Open manual incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: 3b2faf00-1df0-4dfd-8fc8-a7585ba16d97
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -600,
          "y": 930
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: ${inputs.TagValueForIndicators}
      indicatorsValues:
        simple: ${playbookQuery.value}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Add tag to indicators.
      id: d5b3bc5c-26cc-43d0-891b-6e223dd14144
      iscommand: true
      name: Tag indicators for review
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: d5b3bc5c-26cc-43d0-891b-6e223dd14144
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -410,
          "y": 600
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.OpenIncidentToReviewIndicatorsManually
          operator: isNotEqualString
          right:
            value:
              simple: "No"
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e371d45d-7496-4200-856c-f77c7209c9fb
      iscommand: false
      name: Open manual incident?
      type: condition
      version: -1
    taskid: e371d45d-7496-4200-856c-f77c7209c9fb
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -410,
          "y": 760
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      indicatorsValues:
        simple: ${playbookQuery.value}
      reason:
        simple: ${inputs.AutoExcludeReason}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Add indicators to XSOAR exclusion list.
      id: 444adddb-eb6b-4c1b-8beb-a4c2d77fb7bf
      iscommand: true
      name: Exclude indicators
      script: Builtin|||excludeIndicators
      type: regular
      version: -1
    taskid: 444adddb-eb6b-4c1b-8beb-a4c2d77fb7bf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": 760
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1075,
        "width": 1430,
        "x": -600,
        "y": 90
      }
    }
  }
