contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 796d3c8a-7527-4ec4-8bc7-0cbcd36bd479
inputs: []
name: uat-test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f4bf7e9e-77c9-4799-8650-44f64c16a619
      iscommand: false
      name: ""
      version: -1
    taskid: f4bf7e9e-77c9-4799-8650-44f64c16a619
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 435a4643-3a3c-4a2e-858a-3c08d861378f
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 435a4643-3a3c-4a2e-858a-3c08d861378f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b0f01e9-0f27-41f8-80d0-f68f17c19780
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 0b0f01e9-0f27-41f8-80d0-f68f17c19780
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
