contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0ae45877-0dc1-4e45-847a-004ae92a34e6
inputs: []
name: new-modify
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: faba9178-5131-4404-85e5-dd72acf229b1
      iscommand: false
      name: ""
      version: -1
    taskid: faba9178-5131-4404-85e5-dd72acf229b1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0301ba0c-693a-4228-8685-a8d5b65ed6e6
      iscommand: false
      name: "1"
      type: regular
      version: -1
    taskid: 0301ba0c-693a-4228-8685-a8d5b65ed6e6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 290
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6d0467af-1467-41b4-8fab-36bf045aaf36
      iscommand: false
      name: "2"
      type: regular
      version: -1
    taskid: 6d0467af-1467-41b4-8fab-36bf045aaf36
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 510
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c0991136-7c88-46ad-841f-aa4c4e884505
      iscommand: false
      name: "3"
      type: regular
      version: -1
    taskid: c0991136-7c88-46ad-841f-aa4c4e884505
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 750
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: re
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 54c3f658-de5f-4b78-85a4-aeacc61ec681
      iscommand: false
      name: "4"
      script: Print
      type: regular
      version: -1
    taskid: 54c3f658-de5f-4b78-85a4-aeacc61ec681
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 960
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1005,
        "width": 440,
        "x": 450,
        "y": 50
      }
    }
  }
