contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.0.0
    packID: HelloWorld
    packName: HelloWorld
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: Deprecated. No available replacement.
id: HelloWorld Scan
inputs:
- description: Hostname to run the scan against. By default takes ${Endpoint.Hostname}
    from the context as the input.
  key: Hostname
  playbookInputQuery: null
  required: true
  value:
    complex:
      accessor: Hostname}
      root: ${Endpoint
- description: 'Output report format: can be "json" (output parsed and written in
    the Context) or "file" (saved as an attachment). By default is "json".'
  key: Report Format
  playbookInputQuery: null
  required: true
  value:
    simple: json
- description: How often to check for the scan to be completed (minutes)
  key: Interval
  playbookInputQuery: null
  required: true
  value:
    simple: "1"
- description: How long to wait for the scan to be completed before timing out (minutes)
  key: Timeout
  playbookInputQuery: null
  required: true
  value:
    simple: "15"
name: HelloWorld Scan
outputs:
- contextPath: HelloWorld.Scan.entity.entity-id
  description: Scanned entity ID.
- contextPath: HelloWorld.Scan.entity.ip_address
  description: Scanned entity IP address.
- contextPath: HelloWorld.Scan.entity.type
  description: Scanned entity type.
- contextPath: HelloWorld.Scan.entity.vulnerability_status
  description: Scanned entity vulnerability status.
- contextPath: HelloWorld.Scan.entity.vulns
  description: Scanned entity CVE.
- contextPath: CVE.ID
  description: The ID of the CVE.
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file.
- contextPath: InfoFile.Extension
  description: The extension of the report file.
- contextPath: InfoFile.Name
  description: The name of the report file.
- contextPath: InfoFile.Info
  description: The info of the report file.
- contextPath: InfoFile.Size
  description: The size of the report file.
- contextPath: InfoFile.Type
  description: The type of the report file.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dafe8c51-8798-4472-8b0d-b9cfc1b1b613
      iscommand: false
      name: ""
      version: -1
    taskid: dafe8c51-8798-4472-8b0d-b9cfc1b1b613
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        simple: ${inputs.Hostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Start a HelloWorld scan on an asset, identified from by ${input.Hostname}
        key.
      id: 6b00143b-8523-4436-8950-adfd73869e64
      iscommand: true
      name: Start a Hello World Scan
      script: '|||helloworld-scan-start'
      type: regular
      version: -1
    taskid: 6b00143b-8523-4436-8950-adfd73869e64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${HelloWorld.Scan.scan_id}
      Interval:
        simple: ${inputs.Interval}
      PollingCommandArgName:
        simple: scan_id
      PollingCommandName:
        simple: helloworld-scan-status
      Timeout:
        simple: ${inputs.Timeout}
      dt:
        simple: HelloWorld.Scan(val.status !== 'COMPLETE').scan_id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 658053d1-8d16-45b8-8241-f0e0f1f9d982
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 658053d1-8d16-45b8-8241-f0e0f1f9d982
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      format:
        simple: ${inputs.Report Format}
      scan_id:
        simple: ${HelloWorld.Scan.scan_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve scan status in Context or as a File (default) for a Scan.
      id: 48a7dfde-e420-48b7-8a04-59f423ee4e52
      iscommand: true
      name: Retrieve HelloWorld Scan Results
      script: '|||helloworld-scan-results'
      type: regular
      version: -1
    taskid: 48a7dfde-e420-48b7-8a04-59f423ee4e52
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 480e9af4-1e53-4351-8a6e-3e0d9a369cc0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 480e9af4-1e53-4351-8a6e-3e0d9a369cc0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Hostname
          operator: isNotEmpty
      label: "true"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "true":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the input Hostname is valid (i.e. is not Empty), do not
        run the scan otherwise.
      id: 0449752f-d12c-45e8-8bb9-1465da7e57f7
      iscommand: false
      name: Is Hostname set?
      type: condition
      version: -1
    taskid: 0449752f-d12c-45e8-8bb9-1465da7e57f7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Hostname is not set, cannot run the playbook!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 77b84196-1f07-4013-8f31-863e7315d3b4
      iscommand: false
      name: Print Error
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 77b84196-1f07-4013-8f31-863e7315d3b4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
