contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 2.1.17
    packID: PAN-OS
    packName: PAN-OS by Palo Alto Networks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Commit the PAN-OS Panorama or Firewall configuration. If specified as
  Panorama, it also pushes the Policies to the specified Device Group in the instance.
id: PAN-OS Commit Configuration v2
inputs:
- description: ""
  key: device-group
  playbookInputQuery: null
  required: false
  value: {}
name: PAN-OS Commit Configuration v2
outputs:
- contextPath: Panorama.Commit.JobID
  description: The job ID to commit.
- contextPath: Panorama.Commit.Status
  description: The commit status.
- contextPath: Panorama.Commit.Description
  description: The commit description from the the command input.
- contextPath: Panorama.Push.DeviceGroup
  description: The device group in which the policies were pushed.
- contextPath: Panorama.Push.JobID
  description: The job ID of the policies that were pushed.
- contextPath: Panorama.Push.Status
  description: The push status.
- contextPath: Panorama.Push.Warnings
  description: The push warnings.
- contextPath: Panorama.Push.Errors
  description: The push errors.
- contextPath: Panorama.Push.Details
  description: The job ID details.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 72f6ac89-7d29-48cd-8fc8-a87a469d368e
      iscommand: false
      name: ""
      version: -1
    taskid: 72f6ac89-7d29-48cd-8fc8-a87a469d368e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 370,
          "y": -250
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Panorama
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify that there is a valid instance of Palo Alto Networks PAN-OS
        enabled.
      id: 9c71e52d-9168-48c7-85bf-c1ed81ed2c16
      iscommand: false
      name: Is Palo Alto Networks PAN-OS enabled?
      type: condition
      version: -1
    taskid: 9c71e52d-9168-48c7-85bf-c1ed81ed2c16
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 370,
          "y": -100
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      interval_in_seconds:
        simple: "60"
      polling:
        simple: "true"
      timeout:
        simple: "600"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Commit Palo Alto Firewall or Panorama
      id: ba35b0ca-2a3c-4a01-8554-7599c67c8d6a
      iscommand: true
      name: Commit to Panorama
      script: '|||pan-os-commit'
      type: regular
      version: -1
    taskid: ba35b0ca-2a3c-4a01-8554-7599c67c8d6a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 70
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 952b0224-dd79-4eca-8721-d93bd8edd76a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 952b0224-dd79-4eca-8721-d93bd8edd76a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 370,
          "y": 1960
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      device-group:
        complex:
          root: inputs.device-group
      interval_in_seconds:
        simple: "60"
      polling:
        simple: "true"
      timeout:
        simple: "600"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Push rules from Palo Alto Panorama to the Palo Alto configured
        device group.
      id: cbf70090-8353-41e4-8efb-3290bfd04bcb
      iscommand: true
      name: Push rules to the Panorama device group
      script: '|||pan-os-push-to-device-group'
      type: regular
      version: -1
    taskid: cbf70090-8353-41e4-8efb-3290bfd04bcb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1260
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 2
    scriptarguments:
      job_id:
        complex:
          accessor: Commit.JobID
          root: Panorama
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get commit status
      id: 589fe169-faf7-4986-806f-51eecdb7246c
      iscommand: true
      name: Get Panorama commit status
      script: '|||pan-os-commit-status'
      type: regular
      version: -1
    taskid: 589fe169-faf7-4986-806f-51eecdb7246c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 230
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      cmd:
        simple: <show><system><info></info></system></show>
      extend-context:
        simple: panorama.model=response.result.system.model
      type:
        simple: op
    separatecontext: false
    skipunavailable: false
    task:
      brand: Panorama
      description: Run any command supported in the API.
      id: 326d59a9-9554-4d3a-89f5-b5774735b095
      iscommand: true
      name: Fetch instance info
      script: Panorama|||pan-os
      type: regular
      version: -1
    taskid: 326d59a9-9554-4d3a-89f5-b5774735b095
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 910
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: panorama.model
          operator: isEqualString
          right:
            value:
              simple: Panorama
      label: Panorama
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      Panorama:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Automatically detects the product (Panorama/Firewall).
      id: 0a67cd5e-291c-4cbf-8cf6-1898cd23ef39
      iscommand: false
      name: Identify the instance type
      type: condition
      version: -1
    taskid: 0a67cd5e-291c-4cbf-8cf6-1898cd23ef39
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 1080
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Commit.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: db94418c-0822-4d35-8bdc-6a323ac302d4
      iscommand: false
      name: Was Panorama commit successful?
      type: condition
      version: -1
    taskid: db94418c-0822-4d35-8bdc-6a323ac302d4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 400
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Push.Status
          operator: isEqualString
          right:
            value:
              simple: Completed
      label: "yes"
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: e5e51f27-0ef7-4603-8ff4-6f29c327187f
      iscommand: false
      name: Was Panorama push successful?
      type: condition
      version: -1
    taskid: e5e51f27-0ef7-4603-8ff4-6f29c327187f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1430
        }
      }
  "16":
    continueonerror: true
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Panorama Commit Failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 516e84d7-3bf1-4af1-821d-c7d930835966
      iscommand: false
      name: Print commit error
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 516e84d7-3bf1-4af1-821d-c7d930835966
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 940,
          "y": 570
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Panorama Commit Failed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 58e98f40-8373-4cc1-8346-fe35fd176373
      iscommand: false
      name: Print push error
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 58e98f40-8373-4cc1-8346-fe35fd176373
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 1610
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 3e46d493-9404-476d-8d95-68b8ad017a84
      iscommand: false
      name: Fix errors and commit manually
      type: regular
      version: -1
    taskid: 3e46d493-9404-476d-8d95-68b8ad017a84
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 940,
          "y": 735
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 6e3293ac-bae0-4627-8b89-b25f67466c9f
      iscommand: false
      name: Fix errors and push manually
      type: regular
      version: -1
    taskid: 6e3293ac-bae0-4627-8b89-b25f67466c9f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1140,
          "y": 1780
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "13_5_#default#": 0.1,
      "13_6_Panorama": 0.73,
      "14_12_yes": 0.24,
      "15_17_#default#": 0.2,
      "15_5_yes": 0.1,
      "1_5_#default#": 0.17
    },
    "paper": {
      "dimensions": {
        "height": 2275,
        "width": 1150,
        "x": 370,
        "y": -250
      }
    }
  }
