contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8c4c623d-3e90-4be4-8208-515303f85bf8
inputs: []
name: amir-test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ba6ab088-fac2-47ec-83c1-edd678ea5da1
      iscommand: false
      name: ""
      version: -1
    taskid: ba6ab088-fac2-47ec-83c1-edd678ea5da1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: hello
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8e7e6468-6469-474c-8375-ab77f21da95e
      iscommand: false
      name: amir1
      script: Print
      type: regular
      version: -1
    taskid: 8e7e6468-6469-474c-8375-ab77f21da95e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: amir2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 0cef3032-4b89-4b76-83e4-9e551df92160
      iscommand: false
      name: amir2
      script: Print
      type: regular
      version: -1
    taskid: 0cef3032-4b89-4b76-83e4-9e551df92160
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 490
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
