contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 09b6e1a1-413a-451f-85e9-13d0fbadbdff
inputs: []
name: testing - delete
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1a1b05cb-888a-48cb-84ed-48a553e37b91
      iscommand: false
      name: ""
      version: -1
    taskid: 1a1b05cb-888a-48cb-84ed-48a553e37b91
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7c245f8c-b415-49a0-80ab-0075ef4b639f
      iscommand: false
      name: dfdfdfd
      type: regular
      version: -1
    taskid: 7c245f8c-b415-49a0-80ab-0075ef4b639f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 460
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 505,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
