contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: |-
  Deprecated. Use `Get File Sample By Hash - Generic v3` instead. This playbook returns a file sample correlating to a hash in the war-room using the following sub-playbooks:
  - Get File Sample By Hash - Carbon Black Enterprise Response
  - Get File Sample By Hash - Cylance Protect v2
id: Get File Sample By Hash - Generic v2
inputs:
- description: Get file sample from MD5 input
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: Get file sample from SHA256 input
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
name: Get File Sample By Hash - Generic v2
outputs:
- contextPath: File
  description: File sample object
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e1c3bf5a-d7ba-4062-8877-ad2799d1db03
      iscommand: false
      name: ""
      version: -1
    taskid: e1c3bf5a-d7ba-4062-8877-ad2799d1db03
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Returns to the war-room a file sample correlating to MD5 hashes
        in the input using Carbon Black Enterprise Response integration
      id: 09f337a9-fb19-48ce-8b0f-902e0dc9f047
      iscommand: false
      name: Get File Sample By Hash - Carbon Black Enterprise Response
      playbookName: Get File Sample By Hash - Carbon Black Enterprise Response
      type: playbook
      version: -1
    taskid: 09f337a9-fb19-48ce-8b0f-902e0dc9f047
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b5e5705d-8e32-41bb-8c3b-63c78bd2d14f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b5e5705d-8e32-41bb-8c3b-63c78bd2d14f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook returns a file sample to the war-room given the file's
        SHA256 hash, using Cylance Protect v2 integration.
      id: 3a3ab19d-7b69-4631-847b-27eb7f7f80ee
      iscommand: false
      name: Get File Sample By Hash - Cylance Protect v2
      playbookName: Get File Sample By Hash - Cylance Protect v2
      type: playbook
      version: -1
    taskid: 3a3ab19d-7b69-4631-847b-27eb7f7f80ee
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
