contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 53ffcbae-04f9-4070-801a-66cb0b649ce4
inputs: []
name: amir-new2
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4cbf9123-e130-47a3-8fea-508bd4424494
      iscommand: false
      name: ""
      version: -1
    taskid: 4cbf9123-e130-47a3-8fea-508bd4424494
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "1000"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 209f41b2-6f91-4f5f-86d9-9510a15a16f9
      iscommand: false
      name: "1000"
      script: Print
      type: regular
      version: -1
    taskid: 209f41b2-6f91-4f5f-86d9-9510a15a16f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 540,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 395,
        "width": 470,
        "x": 450,
        "y": 50
      }
    }
  }
