contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0bb6ef82-1d68-4246-8480-e1c336f32d19
inputs: []
name: amir-playbook-commit-only
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c43f8b6-971c-48fb-8092-c8605d963ee6
      iscommand: false
      name: ""
      version: -1
    taskid: 1c43f8b6-971c-48fb-8092-c8605d963ee6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 721d75ee-3392-4e21-8325-931a3737357c
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 721d75ee-3392-4e21-8325-931a3737357c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 360
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 405,
        "width": 410,
        "x": 450,
        "y": 50
      }
    }
  }
