contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.3.14
    packID: Gmail
    packName: Gmail
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook searches Gmail to identify and delete emails with similar
  attributes to the malicious email.
id: Search And Delete Emails - Gmail
inputs:
- description: The value of the malicious email's "From" attribute.
  key: From
  playbookInputQuery: null
  required: false
  value: {}
- description: The value of the malicious email's "Subject" attribute.
  key: Subject
  playbookInputQuery: null
  required: false
  value: {}
- description: The value of the malicious email's "AttachmentName" attribute.
  key: AttachmentName
  playbookInputQuery: null
  required: false
  value: {}
- description: The maximum number of search results.
  key: Limit
  playbookInputQuery: null
  required: false
  value:
    simple: "50"
- description: |-
    The deletion type (trash or permanent).
    For permanent choose 'True'.
  key: DeleteType
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: Limit the search to the current week (true/false).
  key: SearchThisWeek
  playbookInputQuery: null
  required: false
  value:
    simple: "true"
name: Search And Delete Emails - Gmail
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5a9d84d3-4a84-49e7-8972-8fbdb62dd634
      iscommand: false
      name: ""
      version: -1
    taskid: 5a9d84d3-4a84-49e7-8972-8fbdb62dd634
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 100,
          "y": 60
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Gmail
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the Gmail integration is enabled.
      id: 151131f2-0195-46a9-81cd-17c5a6edf387
      iscommand: false
      name: Is Gmail enabled?
      type: condition
      version: -1
    taskid: 151131f2-0195-46a9-81cd-17c5a6edf387
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3599887c-fcc3-4676-8b31-2759f6dae2f0
      iscommand: false
      name: Search all mailboxes in Gmail
      type: title
      version: -1
    taskid: 3599887c-fcc3-4676-8b31-2759f6dae2f0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 100,
          "y": 400
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      after:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
          - args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: ^[^T]+
            operator: RegexExtractAll
      filename:
        complex:
          root: inputs.AttachmentName
      from:
        complex:
          root: inputs.From
      include-spam-trash:
        simple: "True"
      max-results:
        complex:
          root: inputs.Limit
      subject:
        complex:
          root: inputs.Subject
          transformers:
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches the Gmail records for all Google users from the last 7
        days.
      id: 6f955c81-9371-410c-8bcc-a721f65608e1
      iscommand: true
      name: Search Gmail for similar emails last 7 days
      script: '|||gmail-search-all-mailboxes'
      type: regular
      version: -1
    taskid: 6f955c81-9371-410c-8bcc-a721f65608e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": 930
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      message-id:
        complex:
          accessor: ID
          root: GmailSearchResults
      permanent:
        complex:
          root: inputs.DeleteType
      user-id:
        complex:
          accessor: Mailbox
          root: GmailSearchResults
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Deletes an email from the user's mailbox.
      id: a9931d1e-df8a-45da-879b-d09f66d477c7
      iscommand: true
      name: Delete emails from Gmail
      script: '|||gmail-delete-mail'
      type: regular
      version: -1
    taskid: a9931d1e-df8a-45da-879b-d09f66d477c7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 2170
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Gmail.Subject
                    operator: isEqualString
                    right:
                      iscontext: true
                      value:
                        simple: inputs.Subject
                root: Gmail.Subject
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if similar emails were found.
      id: 07d73995-ee71-492e-807e-9384c484724c
      iscommand: false
      name: Were similar emails found?
      type: condition
      version: -1
    taskid: 07d73995-ee71-492e-807e-9384c484724c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100,
          "y": 1120
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 061e87a9-eb34-4a37-8611-7ff36f771121
      iscommand: false
      name: Delete similar emails
      type: title
      version: -1
    taskid: 061e87a9-eb34-4a37-8611-7ff36f771121
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1830
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f91ff578-311c-4f1b-8338-39c6337656aa
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f91ff578-311c-4f1b-8338-39c6337656aa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 100,
          "y": 2350
        }
      }
  "9":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.SearchThisWeek
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Whether to limit the search time range to a week.
      id: e4fcf874-1d62-40e8-8b0b-54110b5408b6
      iscommand: false
      name: 'Search only a week time range? '
      type: condition
      version: -1
    taskid: e4fcf874-1d62-40e8-8b0b-54110b5408b6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 100,
          "y": 540
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      daysAgo:
        simple: "7"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: c62f6396-a63c-484d-840b-a4ae58a7ec3c
      iscommand: false
      name: Set time range
      script: GetTime
      type: regular
      version: -1
    taskid: c62f6396-a63c-484d-840b-a4ae58a7ec3c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": 750
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      after:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: TimeStampToDate
          - args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: ^[^T]+
            operator: RegexExtractAll
      filename:
        complex:
          root: inputs.AttachmentName
      from:
        complex:
          root: inputs.From
      include-spam-trash:
        simple: "True"
      max-results:
        complex:
          root: inputs.Limit
      subject:
        complex:
          root: inputs.Subject
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Searches the Gmail records for all Google users to find similar
        emails.
      id: 5a461fd8-77a4-486b-834c-10c4a9a81571
      iscommand: true
      name: Search Gmail for similar emails
      script: '|||gmail-search-all-mailboxes'
      type: regular
      version: -1
    taskid: 5a461fd8-77a4-486b-834c-10c4a9a81571
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 930
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "Yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Reviews the Gmail search results and decides whether to delete all of the emails.
        Note: You cannot delete a subset of the emails.

        **Found emails details:**

        Users:
        *${GmailTo}*

        Email IDs:
        *${GmailSearchResults.ID}*
      id: 334b71e3-238f-4f87-8f8d-70da906f712d
      iscommand: false
      name: Should the found emails be deleted from Gmail?
      type: condition
      version: -1
    taskid: 334b71e3-238f-4f87-8f8d-70da906f712d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1980
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: GmailSearchResults
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Gmail.Subject
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.Subject
          root: Gmail
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: From the retrieved emails, extracts only emails with a subject
        identical to the searched email's subject.
      id: cc9c4b4c-dbf5-4696-82f5-f19c331f90da
      iscommand: false
      name: Extract similar emails
      script: Set
      type: regular
      version: -1
    taskid: cc9c4b4c-dbf5-4696-82f5-f19c331f90da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1320
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      text:
        complex:
          accessor: To
          root: GmailSearchResults
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Extracts email addresses from the "To" fields.
      id: e761048e-6e11-42ee-8591-dd470c72cd2b
      iscommand: true
      name: Extract "To" emails
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: e761048e-6e11-42ee-8591-dd470c72cd2b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1480
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: GmailTo
      value:
        complex:
          accessor: Email
          root: ExtractedIndicators
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 3cba94cc-9e68-4dd2-8d94-dfa56b808f0c
      iscommand: false
      name: Remove duplicates
      script: Set
      type: regular
      version: -1
    taskid: 3cba94cc-9e68-4dd2-8d94-dfa56b808f0c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1650
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "12_5_Yes": 0.44,
      "12_8_#default#": 0.46,
      "1_2_yes": 0.39,
      "1_8_#default#": 0.22,
      "6_8_#default#": 0.19,
      "9_10_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 2355,
        "width": 790,
        "x": 100,
        "y": 60
      }
    }
  }
