contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d5511a97-44ce-40d9-8a49-71e949e48715
inputs: []
name: ex vc
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0276aca0-6eca-4017-83e9-29e5da121956
      iscommand: false
      name: ""
      version: -1
    taskid: 0276aca0-6eca-4017-83e9-29e5da121956
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: hu
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a2e59c69-aeac-4050-844d-27e97e8f131f
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: a2e59c69-aeac-4050-844d-27e97e8f131f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 430,
          "y": 270
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 315,
        "width": 400,
        "x": 430,
        "y": 50
      }
    }
  }
