contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 6.0.4
    packID: CortexXDR
    packName: Cortex XDR by Palo Alto Networks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Calculates a severity for the incident based on the involvement of risky
  users or risky hosts in the incident, as determined by the Cortex XDR ITDR module.
id: Calculate Severity - Cortex XDR Risky Assets
inputs:
- description: An object of risky users and their corresponding scores, as outputted
    by the "xdr-list-risky-users" command.
  key: XDRRiskyUsers
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: RiskyUser
      root: PaloAltoNetworksXDR
      transformers:
      - operator: uniq
- description: An object of risky hosts and their corresponding scores, as outputted
    by the "xdr-list-risky-hosts" command.
  key: XDRRiskyHosts
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: RiskyHost
      root: PaloAltoNetworksXDR
      transformers:
      - operator: uniq
name: Calculate Severity - Cortex XDR Risky Assets
outputs:
- contextPath: Severities.XDRUserSeverity
  description: The severity evaluated by the highest risk level associated with the
    Cortex XDR user. Can be Low, Medium or High.
  type: unknown
- contextPath: Severities.XDRHostSeverity
  description: The severity evaluated by the highest risk level associated with the
    Cortex XDR host. Can be Low, Medium or High.
  type: unknown
starttaskid: "0"
system: true
tags:
- XDR
- ITDR
- Severity
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8d8663fb-4ab5-4361-81d5-dc1b7ab9892d
      iscommand: false
      name: ""
      version: -1
    taskid: 8d8663fb-4ab5-4361-81d5-dc1b7ab9892d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f0e37a36-7a05-4657-8ff1-fe267d847e96
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f0e37a36-7a05-4657-8ff1-fe267d847e96
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 820
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: risk_level
                root: inputs.XDRRiskyUsers
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is a risky user, as outputted by the "xdr-list-risky-users"
        command.
      id: 720afdc3-e823-421a-8762-960d88a19fc7
      iscommand: false
      name: Is there a risky user?
      type: condition
      version: -1
    taskid: 720afdc3-e823-421a-8762-960d88a19fc7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1150,
          "y": 190
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a61889bf-859c-4033-8776-67b032d62d19
      iscommand: false
      name: No Risky Hosts
      type: title
      version: -1
    taskid: a61889bf-859c-4033-8776-67b032d62d19
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -1100,
          "y": 630
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Severities.XDRUserSeverity
      value:
        simple: High
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity associated with the Cortex XDR users to "High".
      id: ed1d3519-1a67-454b-84d7-ef2f8d3e93cd
      iscommand: false
      name: Set user severity to high
      script: Set
      type: regular
      version: -1
    taskid: ed1d3519-1a67-454b-84d7-ef2f8d3e93cd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1570,
          "y": 615
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Severities.XDRUserSeverity
      value:
        simple: Medium
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity associated with the Cortex XDR users to "Medium".
      id: 31dbc88b-bf88-4b8d-8ef5-883ec5dad3c8
      iscommand: false
      name: Set user severity to medium
      script: Set
      type: regular
      version: -1
    taskid: 31dbc88b-bf88-4b8d-8ef5-883ec5dad3c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1150,
          "y": 615
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Severities.XDRUserSeverity
      value:
        simple: Low
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity associated with the Cortex XDR users to "Low".
      id: ebb3abbe-af39-4634-8b3b-a8a7626d38aa
      iscommand: false
      name: Set user severity to low
      script: Set
      type: regular
      version: -1
    taskid: ebb3abbe-af39-4634-8b3b-a8a7626d38aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 740,
          "y": 615
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: risk_level
                root: inputs.XDRRiskyHosts
          operator: isNotEmpty
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is a risky host, as outputted by the "xdr-list-risky-hosts"
        command.
      id: c664dcd0-2767-4a2a-87df-78f20e41bc19
      iscommand: false
      name: Is there a risky host?
      type: condition
      version: -1
    taskid: c664dcd0-2767-4a2a-87df-78f20e41bc19
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -210,
          "y": 190
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.XDRRiskyUsers.risk_level
                    operator: isEqualString
                    right:
                      value:
                        simple: HIGH
                root: inputs.XDRRiskyUsers
          operator: isNotEmpty
          right:
            value: {}
      label: High
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.XDRRiskyUsers.risk_level
                    operator: isEqualString
                    right:
                      value:
                        simple: MED
                root: inputs.XDRRiskyUsers
          operator: isNotEmpty
      label: Medium
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.XDRRiskyUsers.risk_level
                    operator: isEqualString
                    right:
                      value:
                        simple: LOW
                root: inputs.XDRRiskyUsers
          operator: isNotEmpty
      label: Low
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      High:
      - "6"
      Low:
      - "8"
      Medium:
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks which user has the highest risk level, and sets a severity
        output accordingly.
      id: 123cb178-a4d8-4bbf-8b37-e4fc5cdf9106
      iscommand: false
      name: What is the highest risk level associated with the users?
      type: condition
      version: -1
    taskid: 123cb178-a4d8-4bbf-8b37-e4fc5cdf9106
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1150,
          "y": 405
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fdcaa56e-e26c-41e4-82ba-5f160af496df
      iscommand: false
      name: No Risky Users
      type: title
      version: -1
    taskid: fdcaa56e-e26c-41e4-82ba-5f160af496df
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 2000,
          "y": 630
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.XDRRiskyHosts.risk_level
                    operator: isEqualString
                    right:
                      value:
                        simple: HIGH
                root: inputs.XDRRiskyHosts
          operator: isNotEmpty
          right:
            value: {}
      label: High
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.XDRRiskyHosts.risk_level
                    operator: isEqualString
                    right:
                      value:
                        simple: MED
                root: inputs.XDRRiskyHosts
          operator: isNotEmpty
      label: Medium
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: inputs.XDRRiskyHosts.risk_level
                    operator: isEqualString
                    right:
                      value:
                        simple: LOW
                root: inputs.XDRRiskyHosts
          operator: isNotEmpty
      label: Low
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      High:
      - "17"
      Low:
      - "15"
      Medium:
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks which host has the highest risk level, and sets a severity
        output accordingly.
      id: 2130a3eb-dea1-467b-8334-bc6ab3b3a496
      iscommand: false
      name: What is the highest risk level associated with the hosts?
      type: condition
      version: -1
    taskid: 2130a3eb-dea1-467b-8334-bc6ab3b3a496
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -210,
          "y": 405
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Severities.XDRHostSeverity
      value:
        simple: Low
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity associated with the Cortex XDR hosts to "Low".
      id: fd33a226-d4bc-4dba-8a2b-5cb4475cd38d
      iscommand: false
      name: Set host severity to low
      script: Set
      type: regular
      version: -1
    taskid: fd33a226-d4bc-4dba-8a2b-5cb4475cd38d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 210,
          "y": 615
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Severities.XDRHostSeverity
      value:
        simple: Medium
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity associated with the Cortex XDR hosts to "Medium".
      id: 5b3ed38c-c292-4d01-89a9-d788c8213403
      iscommand: false
      name: Set host severity to medium
      script: Set
      type: regular
      version: -1
    taskid: 5b3ed38c-c292-4d01-89a9-d788c8213403
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -210,
          "y": 615
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Severities.XDRHostSeverity
      value:
        simple: High
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Sets the severity associated with the Cortex XDR hosts to "High".
      id: 2d888db6-9550-4b5d-8ed4-734c37b7a164
      iscommand: false
      name: Set host severity to high
      script: Set
      type: regular
      version: -1
    taskid: 2d888db6-9550-4b5d-8ed4-734c37b7a164
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -640,
          "y": 615
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 835,
        "width": 3480,
        "x": -1100,
        "y": 50
      }
    }
  }
