contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  Enrich URLs using one or more integrations.

  URL enrichment includes:
  * SSL verification for URLs
  * Threat information
  * Providing of URL screenshots
  * URL Reputation using !url
id: URL Enrichment - Generic v2
inputs:
- description: URLs to enrich.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
      transformers:
      - operator: uniq
- description: Should the system take safe screenshots of input URLs?
  key: Rasterize
  playbookInputQuery: null
  required: false
  value:
    simple: "True"
- description: Should the system perform SSL certificate verification on the URLs?
  key: VerifyURL
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
- description: |-
    Define if you would like to use the !url command.
    Note: This input should be used whenever there is no auto-extract enabled in the investigation flow.
    Possible values: True / False.
  key: UseReputationCommand
  playbookInputQuery: null
  required: true
  value:
    simple: "False"
name: URL Enrichment - Generic v2
outputs:
- contextPath: URL
  description: The URL object.
  type: uknown
- contextPath: URL.Data
  description: The enriched URL.
  type: string
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
- contextPath: URL.Malicious
  description: Whether the detected URL was malicious.
  type: unknown
- contextPath: URL.Vendor
  description: Vendor that labeled the URL as malicious.
  type: string
- contextPath: URL.Description
  description: Additional information for the URL.
  type: string
- contextPath: URL.Malicious.Vendor
  description: For malicious URLs, the vendor that made the decision.
- contextPath: URL.Malicious.Description
  description: For malicious URLs, the reason that the vendor made the decision.
- contextPath: DBotScore.Indicator
  description: The indicator
  type: string
- contextPath: DBotScore.Type
  description: The indicator's type
  type: string
- contextPath: DBotScore.Vendor
  description: The reputation vendor
  type: string
- contextPath: DBotScore.Score
  description: The reputation score
  type: number
- contextPath: DBotScore.Reliability
  description: Reliability of the source providing the intelligence data.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e1a236ab-b35b-4b70-84a7-3ca08b9bbe95
      iscommand: false
      name: ""
      version: -1
    taskid: e1a236ab-b35b-4b70-84a7-3ca08b9bbe95
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 490,
          "y": -39
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "37"
      "yes":
      - "29"
      - "31"
      - "38"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determine whtether the playbook's input contains at least one URL.
      id: f7198345-28e9-4d23-8e05-7d4b443f807b
      iscommand: false
      name: Are there URLs?
      type: condition
      version: -1
    taskid: f7198345-28e9-4d23-8e05-7d4b443f807b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 155
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7956570c-4a34-462b-84aa-0f8c6d01cf43
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7956570c-4a34-462b-84aa-0f8c6d01cf43
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1125
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: Rasterize
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Rasterize integration
        enabled.
      id: 426d5e5a-76ec-4310-8157-e3ce1795f88f
      iscommand: false
      name: 'Is Rasterize integration enabled? '
      script: Exists
      type: condition
      version: -1
    taskid: 426d5e5a-76ec-4310-8157-e3ce1795f88f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -40,
          "y": 710
        }
      }
  "26":
    continueonerror: true
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rasterize
      description: Gets a screenshot of the URL page.
      id: 6b4658d8-898a-47b0-8b7d-09e6400c6109
      iscommand: true
      name: Get URL screenshot
      script: Rasterize|||rasterize
      tags:
      - url_screenshots
      type: regular
      version: -1
    taskid: 6b4658d8-898a-47b0-8b7d-09e6400c6109
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 920
        }
      }
  "27":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.Rasterize
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the playbook's Rasterize input is set to "True", which
        determines whether screenshots of the URLs are created.
      id: 71af55e1-a11a-42f9-84f6-ce3ce93e17ce
      iscommand: false
      name: Capture screenshots of the URL?
      type: condition
      version: -1
    taskid: 71af55e1-a11a-42f9-84f6-ce3ce93e17ce
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -40,
          "y": 500
        }
      }
  "29":
    continueonerrortype: ""
    id: "29"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fc4755c-5a08-4f90-8bab-12c892b21df4
      iscommand: false
      name: URL Screenshots
      type: title
      version: -1
    taskid: 7fc4755c-5a08-4f90-8bab-12c892b21df4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -40,
          "y": 360
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 11224752-fee9-4a8f-82c0-5af370081779
      iscommand: false
      name: URL Verification
      type: title
      version: -1
    taskid: 11224752-fee9-4a8f-82c0-5af370081779
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 489.5,
          "y": 360
        }
      }
  "32":
    continueonerrortype: ""
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      url:
        complex:
          root: inputs.URL
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Verify URL SSL certificate
      id: 84825bf9-7b64-4953-8ba8-e4d4d1f6d884
      iscommand: false
      name: Verify SSL for URLs
      script: URLSSLVerification
      type: regular
      version: -1
    taskid: 84825bf9-7b64-4953-8ba8-e4d4d1f6d884
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 710
        }
      }
  "33":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.VerifyURL
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "32"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the playbook's VerifyURL input is set to "True", to determine
        whether to perform SSL verification on the URLs.
      id: 0a60d379-a6c4-449e-87e2-4939b8d0ad13
      iscommand: false
      name: Verify URLs?
      type: condition
      version: -1
    taskid: 0a60d379-a6c4-449e-87e2-4939b8d0ad13
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 500
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 395ad908-d5b6-4449-8665-b085546d0d42
      iscommand: false
      name: No URLs
      type: title
      version: -1
    taskid: 395ad908-d5b6-4449-8665-b085546d0d42
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -510,
          "y": 360
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 704516ae-95d9-4ef5-8772-1958046fcac7
      iscommand: false
      name: URL Reputation
      type: title
      version: -1
    taskid: 704516ae-95d9-4ef5-8772-1958046fcac7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 360
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Checks the reputation of a URL.
      id: 0a97859d-7608-47b2-8c81-38009df2a4dd
      iscommand: true
      name: Check Reputation
      script: '|||url'
      type: regular
      version: -1
    taskid: 0a97859d-7608-47b2-8c81-38009df2a4dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 710
        }
      }
  "40":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UseReputationCommand
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "39"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if should run URL reputation command
      id: e0b1281a-38c2-4cbd-8d6d-4330057e5729
      iscommand: false
      name: Should use !url command?
      type: condition
      version: -1
    taskid: e0b1281a-38c2-4cbd-8d6d-4330057e5729
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 500
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "25_24_#default#": 0.53,
      "25_26_yes": 0.47,
      "27_25_yes": 0.5,
      "33_24_#default#": 0.13,
      "33_32_yes": 0.67
    },
    "paper": {
      "dimensions": {
        "height": 1229,
        "width": 1920,
        "x": -510,
        "y": -39
      }
    }
  }
