contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook isolates a given endpoint using various endpoint product integrations.
  Make sure to provide valid playbook inputs for the integration you are using.
id: Isolate Endpoint - Generic V2
inputs:
- description: The host name of the endpoint to isolate.
  key: Endpoint_hostname
  playbookInputQuery: null
  required: false
  value: {}
- description: The IP of the endpoint to isolate.
  key: Endpoint_ip
  playbookInputQuery: null
  required: false
  value: {}
- description: The ID of the endpoint to isolate.
  key: Endpoint_id
  playbookInputQuery: null
  required: false
  value: {}
name: Isolate Endpoint - Generic V2
outputs:
- contextPath: Endpoint
  description: The isolated endpoint.
  type: string
- contextPath: Traps.Isolate.EndpointID
  description: The ID of the endpoint.
  type: string
- contextPath: Traps.IsolateResult.Status
  description: The status of the isolation operation.
  type: string
- contextPath: Cybereason.Machine
  description: The Cybereason machine name.
- contextPath: Cybereason.IsIsolated
  description: Whether the machine is isolated.
- contextPath: Endpoint.Hostname
  description: The host name of the endpoint.
- contextPath: PaloAltoNetworksXDR.Endpoint.endpoint_id
  description: The endpoint ID.
- contextPath: PaloAltoNetworksXDR.Endpoint.endpoint_name
  description: The endpoint name.
- contextPath: PaloAltoNetworksXDR.Endpoint.endpoint_status
  description: The status of the endpoint.
- contextPath: PaloAltoNetworksXDR.Endpoint.ip
  description: The endpoint's IP address.
- contextPath: PaloAltoNetworksXDR.Endpoint.is_isolated
  description: Whether the endpoint is isolated.
- contextPath: MicrosoftATP.MachineAction.ID
  description: The machine action ID.
  type: string
- contextPath: MicrosoftATP.IsolateList
  description: The IDs of the machines that were isolated.
  type: string
- contextPath: MicrosoftATP.NonIsolateList
  description: The IDs of the machines that will not be isolated.
  type: string
- contextPath: MicrosoftATP.IncorrectIDs
  description: Incorrect device IDs entered.
  type: string
- contextPath: MicrosoftATP.IncorrectHostnames
  description: Incorrect device host names entered.
  type: string
- contextPath: MicrosoftATP.IncorrectIPs
  description: Incorrect device IPs entered.
  type: string
- contextPath: Core.Isolation.endpoint_id
  description: The ID of the isolated endpoint.
  type: string
- contextPath: CarbonBlackEDR.Sensor
  description: The sensor info.
  type: unknown
- contextPath: CarbonBlackEDR.Sensor.id
  description: The ID of this sensor.
- contextPath: CarbonBlackEDR.Sensor.is_isolating
  description: Boolean representing the sensor-reported isolation status.
- contextPath: CarbonBlackEDR.Sensor.status
  description: The sensor status.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
      - "7"
      - "9"
      - "10"
      - "12"
      - "13"
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 20f01f93-7b37-4f3f-8c17-a466dac351ef
      iscommand: false
      name: ""
      version: -1
    taskid: 20f01f93-7b37-4f3f-8c17-a466dac351ef
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 050d36dd-0ec3-4490-827e-e210ac5e9a04
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 050d36dd-0ec3-4490-827e-e210ac5e9a04
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Hostname:
        complex:
          root: inputs.Endpoint_hostname
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook isolates an endpoint based on the hostname provided.
      id: 31a268a0-3862-4dcb-8549-b55d0ad936a0
      iscommand: false
      name: Isolate Endpoint - Cybereason
      playbookName: Isolate Endpoint - Cybereason
      type: playbook
      version: -1
    taskid: 31a268a0-3862-4dcb-8549-b55d0ad936a0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id:
        complex:
          root: inputs.Endpoint_id
      hostname:
        complex:
          root: inputs.Endpoint_hostname
      ip_list:
        complex:
          root: inputs.Endpoint_ip
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook accepts an XDR endpoint ID and isolates it using
        the 'Palo Alto Networks Cortex XDR - Investigation and Response' integration.
      id: 46562ad2-14ed-4064-8ce8-9adfb791d660
      iscommand: false
      name: Cortex XDR - Isolate Endpoint
      playbookName: Cortex XDR - Isolate Endpoint
      type: playbook
      version: -1
    taskid: 46562ad2-14ed-4064-8ce8-9adfb791d660
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Device_id:
        complex:
          root: inputs.Endpoint_id
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook will auto isolate endpoints by the device ID that
        was provided in the playbook.
      id: 2604374d-9538-4451-8064-2f5bb5c6dd81
      iscommand: false
      name: Crowdstrike Falcon - Isolate Endpoint
      playbookId: Crowdstrike Falcon - Isolate Endpoint
      type: playbook
      version: -1
    taskid: 2604374d-9538-4451-8064-2f5bb5c6dd81
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Endpoint_id:
        complex:
          root: inputs.Endpoint_id
      Hostname:
        complex:
          root: inputs.Endpoint_hostname
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook will auto isolate endpoints by the endpoint ID that
        was provided in the playbook.
      id: 48226108-0787-44b0-80f6-cf333758b5e8
      iscommand: false
      name: FireEye HX - Isolate Endpoint
      playbookName: FireEye HX - Isolate Endpoint
      type: playbook
      version: -1
    taskid: 48226108-0787-44b0-80f6-cf333758b5e8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Device_IP:
        complex:
          root: inputs.Endpoint_ip
      Device_id:
        complex:
          root: inputs.Endpoint_id
      Hostname:
        complex:
          root: inputs.Endpoint_hostname
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: d438379a-5602-49f9-8d6d-404f9dbe3919
      iscommand: false
      name: Microsoft Defender For Endpoint - Isolate Endpoint
      playbookId: Microsoft Defender For Endpoint - Isolate Endpoint
      type: playbook
      version: -1
    taskid: d438379a-5602-49f9-8d6d-404f9dbe3919
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 195
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id:
        complex:
          root: inputs.Endpoint_id
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Isolates the specified endpoint.
      id: 6288e7cc-1f1c-4132-834c-02efaf383aee
      iscommand: true
      name: Core - Isolate Endpoint
      script: '|||core-isolate-endpoint'
      type: regular
      version: -1
    taskid: 6288e7cc-1f1c-4132-834c-02efaf383aee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -380,
          "y": 195
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Hostname:
        complex:
          root: inputs.Endpoint_hostname
      Sensor_id:
        complex:
          root: inputs.Endpoint_id
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Carbon Black Response - isolates an endpoint for a given hostname.
      id: 73a03b52-b75a-4d47-8220-376956270c68
      iscommand: false
      name: Block Endpoint - Carbon Black Response V2.1
      playbookName: Block Endpoint - Carbon Black Response V2.1
      type: playbook
      version: -1
    taskid: 73a03b52-b75a-4d47-8220-376956270c68
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 2960,
        "x": -380,
        "y": 50
      }
    }
  }
