contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  Enrich a file using one or more integrations.

  - Provide threat information
id: File Enrichment - Generic v2
inputs:
- description: File MD5 hash to enrich.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: The file SHA256 hash to enrich.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: The file SHA1 hash to enrich.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
- description: |-
    Define if you would like to use the !file command.
    Note: This input should be used whenever there is no auto-extract enabled in the investigation flow.
    Possible values: True / False.
  key: UseReputationCommand
  playbookInputQuery: null
  required: true
  value:
    simple: "False"
name: File Enrichment - Generic v2
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: string
- contextPath: DBotScore.Type
  description: The indicator type.
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file.
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file.
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision.
  type: string
- contextPath: File.MD5
  description: MD5 hash of the file.
  type: string
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
- contextPath: File
  description: The file object
  type: unknown
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
- contextPath: File.VirusTotal.Scans
  description: The scan object.
  type: unknown
- contextPath: File.VirusTotal.Scans.Source
  description: Vendor that scanned this hash.
- contextPath: File.VirusTotal.Scans.Detected
  description: Whether a scan was detected for this hash (True/False).
- contextPath: File.VirusTotal.Scans.Result
  description: Scan result for this hash - signature, etc.
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 90f7ce25-c27c-4ca9-8fe6-2168349b0702
      iscommand: false
      name: ""
      version: -1
    taskid: 90f7ce25-c27c-4ca9-8fe6-2168349b0702
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 470,
          "y": -180
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: be10b4ea-fb5e-478c-8614-ae684debb82f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: be10b4ea-fb5e-478c-8614-ae684debb82f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 970
        }
      }
  "25":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA256 hash in context.
      id: e607bf1e-fe9b-41bf-8b96-bb9d6d88dd07
      iscommand: false
      name: Is there a SHA256 hash?
      type: condition
      version: -1
    taskid: e607bf1e-fe9b-41bf-8b96-bb9d6d88dd07
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": 320
        }
      }
  "27":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Cylance Protect v2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Cylance Protect v2
        integration enabled.
      id: 27539369-ccb3-441c-89d9-001a4fc03093
      iscommand: false
      name: Is Cylance Protect v2 enabled?
      type: condition
      version: -1
    taskid: 27539369-ccb3-441c-89d9-001a4fc03093
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": 520
        }
      }
  "28":
    continueonerror: true
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      sha256:
        complex:
          root: inputs.SHA256
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cylance Protect v2
      description: Gets threat information from the Cylance Protect v2 integration.
      id: a06a7e73-028d-4c7f-85b1-7f0344db5906
      iscommand: true
      name: Get threat information from Cylance Protect v2
      script: Cylance Protect v2|||cylance-protect-get-threat
      type: regular
      version: -1
    taskid: a06a7e73-028d-4c7f-85b1-7f0344db5906
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 730
        }
      }
  "30":
    continueonerrortype: ""
    id: "30"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      FileHash:
        complex:
          root: inputs.SHA256
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.SHA1
            operator: append
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.MD5
            operator: append
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Get file information using the Virus Total API integration.
      id: f5488926-c247-4181-8824-1c81eac47049
      iscommand: false
      name: File Enrichment - Virus Total (API v3)
      playbookId: File Enrichment - Virus Total (API v3)
      type: playbook
      version: -1
    taskid: f5488926-c247-4181-8824-1c81eac47049
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 320
        }
      }
  "31":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isExists
          right:
            value: {}
        - left:
            iscontext: true
            value:
              simple: inputs.SHA1
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.MD5
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "36"
      - "32"
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA256 hash in context.
      id: 7cf6f2ba-710b-4d71-8860-852707418e81
      iscommand: false
      name: Is there a file hash?
      type: condition
      version: -1
    taskid: 7cf6f2ba-710b-4d71-8860-852707418e81
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 470,
          "y": -50
        }
      }
  "32":
    continueonerrortype: ""
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "33"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aa3b5462-64fd-4033-8812-9d952347a79d
      iscommand: false
      name: Check Reputation Using All Available Integrations
      type: title
      version: -1
    taskid: aa3b5462-64fd-4033-8812-9d952347a79d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -150,
          "y": 160
        }
      }
  "33":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UseReputationCommand
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "34"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if should run file reputation command
      id: e41f1d02-f6ea-45a6-8c43-d858ec8aa875
      iscommand: false
      name: Should use !file command?
      type: condition
      version: -1
    taskid: e41f1d02-f6ea-45a6-8c43-d858ec8aa875
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -150,
          "y": 320
        }
      }
  "34":
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.SHA256
          transformers:
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.MD5
            operator: append
          - args:
              item:
                iscontext: true
                value:
                  simple: inputs.SHA1
            operator: append
          - operator: uniq
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Checks the file reputation of the specified hash.
      id: 260f6a83-ba18-4aca-8eb1-294f470b1c81
      iscommand: true
      name: Check Reputation
      script: '|||file'
      type: regular
      version: -1
    taskid: 260f6a83-ba18-4aca-8eb1-294f470b1c81
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -150,
          "y": 480
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "30"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4d022016-e7a4-454b-85d5-fad65548649c
      iscommand: false
      name: Virus Total enrichment
      type: title
      version: -1
    taskid: 4d022016-e7a4-454b-85d5-fad65548649c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 160
        }
      }
  "36":
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 601042e3-6757-4e60-8293-6c026caba2d1
      iscommand: false
      name: Cylance Protect enrichment
      type: title
      version: -1
    taskid: 601042e3-6757-4e60-8293-6c026caba2d1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 470,
          "y": 160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "25_27_yes": 0.59,
      "25_7_#default#": 0.16,
      "27_28_yes": 0.57,
      "27_7_#default#": 0.21,
      "31_7_#default#": 0.13
    },
    "paper": {
      "dimensions": {
        "height": 1215,
        "width": 1540,
        "x": -150,
        "y": -180
      }
    }
  }
