contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 796d3c8a-7527-4ec4-8bc7-0cbcd36bd479
inputs: []
name: uat-test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f4bf7e9e-77c9-4799-8650-44f64c16a619
      iscommand: false
      name: ""
      version: -1
    taskid: f4bf7e9e-77c9-4799-8650-44f64c16a619
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60b787f2-ed62-4364-865c-523b871ef4ba
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 60b787f2-ed62-4364-865c-523b871ef4ba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 425,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
