contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  Enrich email addresses.
  - Get information from Active Directory for internal addresses
  - Get the domain-squatting reputation for external addresses
  - Email address reputation using !email command
id: Email Address Enrichment - Generic v2.1
inputs:
- description: A CSV list of internal domains. The list will be used to determine
    whether an email address is internal or external.
  key: InternalDomains
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: inputs.InternalDomains
      transformers:
      - operator: uniq
- description: The email addresses to enrich.
  key: Email
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Email.Address
      root: Account
      transformers:
      - operator: uniq
- description: The domains associated with the incident. These domains will be checked
    for domain-squatting.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      filters:
      - - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isNotEmpty
      root: inputs.Domain
      transformers:
      - operator: uniq
- description: |-
    Define if you would like to use the !email command.
    Note: This input should be used whenever there is no auto-extract enabled in the investigation flow.
    Possible values: True / False.
  key: UseReputationCommand
  playbookInputQuery: null
  required: true
  value:
    simple: "False"
name: Email Address Enrichment - Generic v2.1
outputs:
- contextPath: Account
  description: The Account object.
  type: unknown
- contextPath: Account.Email.NetworkType
  description: The email account NetworkType (Internal/External).
  type: string
- contextPath: Account.Email.Distance.Domain
  description: The compared domain.
  type: string
- contextPath: Account.Email.Distance.Value
  description: 'The distance between the email domain and the compared domain. '
  type: number
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 22a55a7c-c942-4d12-84fb-76bce3695b83
      iscommand: false
      name: ""
      version: -1
    taskid: 22a55a7c-c942-4d12-84fb-76bce3695b83
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 497.5,
          "y": 50
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: entry.contents:${Account.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8970ccc7-3ca4-4f5a-879e-f9d0c07c3e5b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 8970ccc7-3ca4-4f5a-879e-f9d0c07c3e5b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1390
        }
      }
  "5":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.Email
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Email
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determines whether the playbook's input contains at least one email
        address.
      id: ad5dcc8d-aedc-4f17-8e45-cdf57fc8eb8c
      iscommand: false
      name: Are there email addresses to check?
      type: condition
      version: -1
    taskid: ad5dcc8d-aedc-4f17-8e45-cdf57fc8eb8c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 497.5,
          "y": 200
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
      - "14"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      domain:
        complex:
          root: inputs.InternalDomains
          transformers:
          - operator: uniq
      email:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Email
              operator: isNotEmpty
          root: inputs.Email
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds a NetworkType attribute to all email addresses. The NetworkType
        attribute determines whether the email address is an internal or external
        email address, according to the domains that were passed as arguments to this
        playbook.
      id: 9c9335fc-12d0-45eb-887e-41f83a6cfae9
      iscommand: false
      name: Classify email addresses as internal or external
      script: IsEmailAddressInternal
      type: regular
      version: -1
    taskid: 9c9335fc-12d0-45eb-887e-41f83a6cfae9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 497.5,
          "y": 400
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1a9686bb-e22f-46a7-8f5e-adf7acffdf3b
      iscommand: false
      name: Internal
      type: title
      version: -1
    taskid: 1a9686bb-e22f-46a7-8f5e-adf7acffdf3b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 785
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7874c1a7-0bae-43cc-8f13-9234c337f491
      iscommand: false
      name: External
      type: title
      version: -1
    taskid: 7874c1a7-0bae-43cc-8f13-9234c337f491
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 840.5,
          "y": 785
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      email:
        complex:
          accessor: Address
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: isEqualString
              right:
                value:
                  simple: Internal
          root: Account.Email
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uses Active Directory to get user information for internal email
        addresses.
      id: e3b298d5-cb30-4440-803e-596597adcc10
      iscommand: true
      name: Get email address info from Active Directory
      script: '|||ad-get-user'
      type: regular
      version: -1
    taskid: e3b298d5-cb30-4440-803e-596597adcc10
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 1175
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Email
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: isEqualString
              right:
                value:
                  simple: External
          root: Account
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there are email addresses with a NetworkType attribute
        value of "External".
      id: 4dbbbdb8-0102-445f-8fc3-d3ed70c32aa3
      iscommand: false
      name: Are there any external email addresses?
      script: Exists
      type: condition
      version: -1
    taskid: 4dbbbdb8-0102-445f-8fc3-d3ed70c32aa3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 840.5,
          "y": 580
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: Email
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: isEqualString
              right:
                value:
                  simple: Internal
          root: Account
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there are email addresses with a NetworkType attribute
        value of "Internal".
      id: 88f0cd9d-90b3-4fdd-8822-1ff788168d00
      iscommand: false
      name: Are there any internal email addresses?
      script: Exists
      type: condition
      version: -1
    taskid: 88f0cd9d-90b3-4fdd-8822-1ff788168d00
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 580
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      domain:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Domain
              operator: isNotEmpty
          root: inputs.Domain
          transformers:
          - operator: uniq
      email:
        complex:
          accessor: Email
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.Address
              operator: isNotEmpty
          root: Account
          transformers:
          - args:
              equalTo:
                value:
                  simple: External
              field:
                value:
                  simple: NetworkType
              getField:
                value:
                  simple: Address
              stringify:
                value:
                  simple: "false"
            operator: WhereFieldEquals
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if an email address's domain is trying to squat other domains
        using Levenshtein distance algorithm.
      id: 9b9a97f6-c855-4d4e-8047-f0306f006a5f
      iscommand: false
      name: Check email addresses for domain-squatting
      script: EmailDomainSquattingReputation
      type: regular
      version: -1
    taskid: 9b9a97f6-c855-4d4e-8047-f0306f006a5f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600.5,
          "y": 1175
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: isEqualString
              right:
                value:
                  simple: Active Directory Query v2
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there's an active instance of the Active Directory Query
        v2 integration enabled.
      id: df11530c-169c-4a9c-8e37-e9ce934a0c8a
      iscommand: false
      name: Is Active Directory Query v2 enabled?
      script: Exists
      type: condition
      version: -1
    taskid: df11530c-169c-4a9c-8e37-e9ce934a0c8a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 172.5,
          "y": 940
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Domain
              operator: isNotEmpty
          root: inputs.Domain
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is at least one domain to check for domain-squatting.
      id: 82034885-dcb2-4c4a-8fa7-1c1514c27e46
      iscommand: false
      name: Is there a domain list input?
      script: Exists
      type: condition
      version: -1
    taskid: 82034885-dcb2-4c4a-8fa7-1c1514c27e46
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 600.5,
          "y": 940
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 358de9fa-efe5-47c2-801f-7c85db0d408b
      iscommand: false
      name: No Email Addresses
      type: title
      version: -1
    taskid: 358de9fa-efe5-47c2-801f-7c85db0d408b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -380,
          "y": 785
        }
      }
  "21":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UseReputationCommand
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if should run email address reputation command
      id: 047c804f-cc74-4eb3-8ea5-7776e5827088
      iscommand: false
      name: Should use !email command?
      type: condition
      version: -1
    taskid: 047c804f-cc74-4eb3-8ea5-7776e5827088
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1080,
          "y": 940
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        complex:
          root: inputs.Email
    separatecontext: false
    skipunavailable: true
    task:
      brand: ""
      description: Checks if an email address was compromised.
      id: 2ac494e5-1a7e-474d-880f-1e1ab655f3ae
      iscommand: true
      name: Check Reputation
      script: '|||email'
      type: regular
      version: -1
    taskid: 2ac494e5-1a7e-474d-880f-1e1ab655f3ae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1080,
          "y": 1160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "13_11_yes": 0.64,
      "13_4_#default#": 0.16,
      "14_10_yes": 0.65,
      "14_4_#default#": 0.17,
      "17_4_#default#": 0.23,
      "18_4_#default#": 0.23,
      "5_20_#default#": 0.35
    },
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 1840,
        "x": -380,
        "y": 50
      }
    }
  }
