contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 2.1.15
    packID: AutoFocus
    packName: AutoFocus by Palo Alto Networks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: "The playbook queries the PANW Autofocus session and samples log data
  for file and traffic indicators, such as SHA256, SHA1, MD5, IP addresses, URLs,
  and domains. \n\nA simple search mode queries Autofocus based on the indicators
  specified in the playbook inputs. Advanced queries can also use with multiple query
  parameters, but require all field names, parameters, and operators (JSON format)
  to be specified. \nWe recommended using the Autofocus UI to create an advanced query,
  exporting it, and pasting it into the relevant playbook inputs. \n\nNote that multiple
  search values should be separated by commas only (without spaces or any special
  characters)."
id: Autofocus - Hunting And Threat Detection
inputs:
- description: |-
    One or more IP addresses to search for in Autofocus simple mode search.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: IPAddress
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    One or more URLs and/or domains to search for in Autofocus simple mode search.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: URLDomain
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    One or more MD5 file hashes to search for in Autofocus simple mode search.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: MD5
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    One or more SHA256 file hashes to search for in Autofocus simple mode search.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: SHA256
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    One or more SHA1 file hashes to search for in Autofocus simple mode search.

    Separate multiple search values by commas only (without spaces or any special characters).
  key: SHA1
  playbookInputQuery: null
  required: false
  value: {}
- description: "Which Autofocus search types should be executed. \n\nPossible values
    are session, sample, tag, or all. Session and sample are the recommended search
    types for this playbook. \n\nSample-based search detects threat indicators or
    identifiers within samples sent to WildFire for analysis. \n\nSession-based search
    detects threat indicators or identifiers within various context details and session
    data provided by samples during sample submission. \n\nTag-based search identifies
    the most popular tags."
  key: Search Type
  playbookInputQuery: null
  required: true
  value: {}
- description: Search scope for sample and session. Possible values are industry,
    organization, global, or all.
  key: Scope
  playbookInputQuery: null
  required: true
  value: {}
- description: |-
    Use the Autofocus advanced search mode to leverage a variety of query options within a sample search. Advanced search requires you to specify all field names, parameters, and operators.

    The query currently supports only JSON format which can be extracted from the Autofocus web console API radio button.
  key: SampleQuery
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Narrow down a sample-based search by specifying the timestamp samples were first uploaded to WildFire for analysis (indicators will be searched within samples after this timestamp).

    Specify the time in ISO 8601 format, for example, 2019-09-12T00:00:00.
  key: Sample first seen
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Narrow down a sample-based search by specifying the timestamp samples were last modified (indicators will be searched within samples after this timestamp).

    Specify the time in ISO 8601 format, for example, 2019-09-12T00:00:00.
  key: Sample last modified
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Use the Autofocus advanced search mode to leverage a variety of query options within a session search. Advanced search requires you to specify all field names, parameters, and operators.

    The query currently supports only JSON format which can be extracted from the Autofocus web console API radio button.
  key: SessionQuery
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Narrow down a session-based search by specifying the query end timestamp (indicators will be searched within sessions before this timestamp).

    Specify the time in ISO 8601 format, for example, 2019-09-12T00:00:00.
  key: Sessions time before
  playbookInputQuery: null
  required: false
  value: {}
- description: |-
    Narrow down a session-based search by specifying the query start timestamp (indicators will be searched within sessions after this timestamp).

    Specify the time in ISO 8601 format, for example, 2019-09-12T00:00:00.
  key: Sessions time after
  playbookInputQuery: null
  required: false
  value: {}
- description: "Filter results by WildFire classification assigned to samples based
    on properties, behaviors, and activities observed for files or email links during
    static and dynamic analysis.\n\nPossible values are malware, benign, phishing,
    and greyware. "
  key: Wildfire Verdict
  playbookInputQuery: null
  required: false
  value: {}
name: Autofocus - Hunting And Threat Detection
outputs:
- contextPath: Autofocus.Samples.HuntingResults
  description: Sample objects containing relevant fields.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Created
  description: The date the file was created.
  type: date
- contextPath: Autofocus.Samples.HuntingResults.Finished
  description: The date the file was finished.
  type: date
- contextPath: Autofocus.Samples.HuntingResults.FileName
  description: The name of the file.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.FileType
  description: The file type.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.SHA1
  description: The SHA1 hash of the file.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.SHA256
  description: The SHA256 hash of the file.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.MD5
  description: The MD5 hash of the file.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Region
  description: The region of the sample.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Tags
  description: The tags attached to the sample.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.TagGroups
  description: The groups of relevant tags.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Verdict
  description: The verdict of the sample.
  type: number
- contextPath: Autofocus.Samples.HuntingResults.Artifact.confidence
  description: The decision confidence.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Artifact.indicator
  description: The indicator that was tested.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Artifact.indicator_type
  description: 'The indicator type, for example: Mutex, User agent, IPv4, Domain.'
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Artifact.b
  description: How many set the artifact as benign.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Artifact.g
  description: How many set the artifact as grayware.
  type: string
- contextPath: Autofocus.Samples.HuntingResults.Artifact.m
  description: How many set the artifact as malicious.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults
  description: Session objects containing relevant fields.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.Seen
  description: The seen date.
  type: date
- contextPath: Autofocus.Sessions.HuntingResults.UploadSource
  description: The source of the uploaded sample.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.ID
  description: The ID of the session. Used to get session details.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.FileName
  description: The name of the file.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.FileURL
  description: The URL of the file.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.SHA256
  description: The SHA256 hash of the file.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.Industry
  description: The related industry.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.Region
  description: The regions of the sessions.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.Tags
  description: The relevant tags.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.app
  description: The associated application name.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.dst_ip
  description: The associated destination IP.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.src_ip
  description: The associated source IP.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.dst_countrycode
  description: The associated destination country code.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.src_countrycode
  description: The associated source country code.
  type: string
- contextPath: Autofocus.Sessions.HuntingResults.dst_port
  description: The associated destination port number.
  type: number
- contextPath: Autofocus.Sessions.HuntingResults.src_port
  description: The associated source port number.
  type: number
- contextPath: Autofocus.Sessions.HuntingResults.user_id
  description: The recipient user ID.
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "156"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: efd174b1-c3ae-48ce-8d14-52e397954612
      iscommand: false
      name: ""
      version: -1
    taskid: efd174b1-c3ae-48ce-8d14-52e397954612
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 590,
          "y": -140
        }
      }
  "153":
    continueonerrortype: ""
    id: "153"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3ab00780-9973-4e65-8271-1f0d598b5fbd
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3ab00780-9973-4e65-8271-1f0d598b5fbd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 590,
          "y": 330
        }
      }
  "155":
    continueonerrortype: ""
    id: "155"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "153"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        complex:
          root: inputs.IPAddress
      Sample first seen:
        complex:
          root: inputs.Sample first seen
      Sample last modified:
        complex:
          root: inputs.Sample last modified
      SampleQuery:
        complex:
          root: inputs.SampleQuery
      Scope:
        complex:
          root: inputs.Scope
      Search Type:
        complex:
          root: inputs.Search Type
      SessionQuery:
        complex:
          root: inputs.SessionQuery
      Sessions time after:
        complex:
          root: inputs.Sessions time after
      Sessions time before:
        complex:
          root: inputs.Sessions time before
      URLDomain:
        complex:
          root: inputs.URLDomain
      Wildfire Verdict:
        complex:
          root: inputs.Wildfire Verdict
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "Queries the PANW Threat Intelligence Autofocus system. Traffic
        indicators such as URLs, IP addresses, and domains can be used to run basic
        queries in the playbook. \nAdvanced search mode queries can also be used with
        multiple query parameters, but require all field names, parameters, and operators
        (JSON format) to be specified. \nWe recommended using the Autofocus UI to
        create an advanced query, exporting it, and pasting it into the relevant playbook
        inputs."
      id: a0015271-705b-4b2d-8d02-d09f2e3d4374
      iscommand: false
      name: Autofocus - Traffic Indicators Hunting
      playbookId: Autofocus - Traffic Indicators Hunting
      type: playbook
      version: -1
    taskid: a0015271-705b-4b2d-8d02-d09f2e3d4374
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 830,
          "y": 160
        }
      }
  "156":
    continueonerrortype: ""
    id: "156"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "153"
      "yes":
      - "155"
      - "158"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: AutoFocus V2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available.
      id: a42c1add-d6d0-43c0-85d3-a0768def4a46
      iscommand: false
      name: Is Autofocus enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: a42c1add-d6d0-43c0-85d3-a0768def4a46
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 590,
          "y": -10
        }
      }
  "158":
    continueonerrortype: ""
    id: "158"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "153"
    note: false
    quietmode: 0
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
      SHA1:
        complex:
          root: inputs.SHA1
      SHA256:
        complex:
          root: inputs.SHA256
      Sample first seen:
        complex:
          root: inputs.Sample first seen
      Sample last modified:
        complex:
          root: inputs.Sample last modified
      SampleQuery:
        complex:
          root: inputs.SampleQuery
      Scope:
        complex:
          root: inputs.Scope
      Search Type:
        complex:
          root: inputs.Search Type
      SessionQuery:
        complex:
          root: inputs.SessionQuery
      Sessions time after:
        complex:
          root: inputs.Sessions time after
      Sessions time before:
        complex:
          root: inputs.Sessions time before
      Wildfire Verdict:
        complex:
          root: inputs.Wildfire Verdict
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: b74e17f5-8ed6-4241-8b1b-ed2d0c65d2e6
      iscommand: false
      name: Autofocus - File Indicators Hunting
      playbookId: Autofocus - File Indicators Hunting
      type: playbook
      version: -1
    taskid: b74e17f5-8ed6-4241-8b1b-ed2d0c65d2e6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 350,
          "y": 160
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "156_153_#default#": 0.32
    },
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 860,
        "x": 350,
        "y": -140
      }
    }
  }
