contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.5.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Retrieves files from endpoints by the file hash or the file path.
id: Get File Sample - Generic
inputs:
- description: The MD5 hash of the file to retrieve.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: The SHA256 hash of the file to retrieve.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: The hostname from which to retrieve the file.
  key: Hostname
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Hostname
      root: Endpoint
- description: The agent ID that should be used to retrieve the file.
  key: AgentID
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: agentid
      root: incident
- description: The full path to the file that needs to be retrieved.
  key: FilePath
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: filepath
      root: incident
- description: Optional - a new name for the retrieved file. If left empty, the filename
    will not change.
  key: NewFilename
  playbookInputQuery: null
  required: false
  value: {}
- description: Whether to unzip zipped files after retrieving them.
  key: UnzipFile
  playbookInputQuery: null
  required: false
  value: {}
- description: 'The tool used to unzip the file. The options are: 7z, zipfile.'
  key: ZipTool
  playbookInputQuery: null
  required: false
  value: {}
- description: The password used to unzip zipped files.
  key: ZipPassword
  playbookInputQuery: null
  required: false
  value: {}
name: Get File Sample - Generic
outputs:
- contextPath: File
  description: File objects. Includes the zipped file and any unzipped files.
  type: unknown
- contextPath: File.Size
  description: The size of the file.
  type: number
- contextPath: File.Type
  description: The type of the file.
  type: string
- contextPath: File.Info
  description: General information about the file.
  type: string
- contextPath: File.MD5
  description: The MD5 hash of the file.
  type: string
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
  type: string
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
  type: string
- contextPath: File.SHA512
  description: The SHA512 hash of the file.
  type: string
- contextPath: File.SSDeep
  description: The SSDeep of the file.
  type: string
- contextPath: File.Extension
  description: The file extension.
  type: string
- contextPath: File.EntryID
  description: The file entry ID.
  type: string
- contextPath: File.Name
  description: The file name.
  type: string
- contextPath: ExtractedFiles
  description: Files that were unzipped.
  type: unknown
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2f9db3d3-0254-4d38-8bce-aa2325da9194
      iscommand: false
      name: ""
      version: -1
    taskid: 2f9db3d3-0254-4d38-8bce-aa2325da9194
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 452.5,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
      NewFilename:
        complex:
          root: inputs.NewFilename
      SHA256:
        complex:
          root: inputs.SHA256
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This playbook returns a file sample correlating to a hash in the War Room using the following sub-playbooks:
        - Get the binary file from Carbon Black by its MD5 hash
        - Get File Sample By Hash - Cylance Protect v2
        - Code42 File Download
      id: 7456030a-675f-4c46-8231-7820167addc6
      iscommand: false
      name: Get File Sample By Hash - Generic v3
      playbookId: Get File Sample By Hash - Generic v3
      type: playbook
      version: -1
    taskid: 7456030a-675f-4c46-8231-7820167addc6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 230,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Agent_ID:
        complex:
          root: inputs.AgentID
      Host:
        complex:
          root: inputs.Hostname
      Path:
        complex:
          root: inputs.FilePath
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |
        This playbook returns a file sample from a specified path and host that you input in the following playbooks:
        - PS Remote Get File Sample From Path
        - Get File Sample From Path - VMware Carbon Black EDR - Live Response API
      id: 5759c2d5-753c-4591-86f6-ff7d4647f306
      iscommand: false
      name: Get File Sample From Path - Generic V3
      playbookId: Get File Sample From Path - Generic V3
      type: playbook
      version: -1
    taskid: 5759c2d5-753c-4591-86f6-ff7d4647f306
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 670,
          "y": 210
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      File:
        complex:
          root: File
      Password:
        complex:
          root: inputs.ZipPassword
      ZipTool:
        complex:
          root: inputs.ZipTool
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook checks whether a file has an extension that supports
        unzipping, and unzips the file.
      id: 0de5f36a-ceca-4ef5-8fc5-8f3268aed0fe
      iscommand: false
      name: Unzip File
      playbookId: Unzip File
      type: playbook
      version: -1
    taskid: 0de5f36a-ceca-4ef5-8fc5-8f3268aed0fe
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 690,
          "y": 600
        }
      }
  "4":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.UnzipFile
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether retrieved files should be unzipped according to
        the playbook inputs.
      id: 0ef94b0c-f547-471f-8af9-2e75834b30ba
      iscommand: false
      name: Should files be unzipped?
      type: condition
      version: -1
    taskid: 0ef94b0c-f547-471f-8af9-2e75834b30ba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 452.5,
          "y": 410
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76635ebc-b129-40a7-804a-6519ff1b15dc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 76635ebc-b129-40a7-804a-6519ff1b15dc
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 452.5,
          "y": 800
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "4_5_#default#": 0.3
    },
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 840,
        "x": 230,
        "y": 50
      }
    }
  }
