contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.4.13
    packID: CommonPlaybooks
    packName: Common Playbooks
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  Enrich IP addresses using one or more integrations.

  - Resolve IP addresses to hostnames (DNS)
  - Provide threat information
  - Separate internal and external IP addresses
  - For internal IP addresses, get host information
id: IP Enrichment - Generic v2
inputs:
- description: The IP address to enrich.
  key: IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      root: IP
      transformers:
      - operator: uniq
- description: 'A list of internal IP ranges to check IP addresses against. The list
    should be provided in CIDR notation, separated by commas. An example of a list
    of ranges would be: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16" (without quotes).
    If a list is not provided, will use default list provided in the IsIPInRanges
    script (the known IPv4 private address ranges).'
  key: InternalRange
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: inputs.InternalRange
      transformers:
      - operator: uniq
- description: Determines whether to convert the IP address to a hostname using a
    DNS query (True/ False).
  key: ResolveIP
  playbookInputQuery: null
  required: true
  value:
    complex:
      root: inputs.ResolveIP
      transformers:
      - args:
          applyIfEmpty: {}
          defaultValue:
            value:
              simple: "False"
        operator: SetIfEmpty
- description: |-
    Define if you would like to use the !IP command.
    Note: This input should be used whenever there is no auto-extract enabled in the investigation flow.
    Possible values: True / False.
  key: UseReputationCommand
  playbookInputQuery: null
  required: true
  value:
    simple: "False"
name: IP Enrichment - Generic v2
outputs:
- contextPath: IP
  description: The IP objects
  type: unknown
- contextPath: DBotScore
  description: Indicator, Score, Type, Vendor
  type: unknown
- contextPath: Endpoint
  description: The Endpoint's object
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6635b28b-bdf1-42cf-88bc-14ad75e9ebe0
      iscommand: false
      name: ""
      version: -1
    taskid: 6635b28b-bdf1-42cf-88bc-14ad75e9ebe0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "24":
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8149db7c-af8d-41e2-85ee-c9fe2efd5040
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 8149db7c-af8d-41e2-85ee-c9fe2efd5040
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      IP:
        complex:
          root: inputs.IP
          transformers:
          - operator: uniq
      InternalRange:
        complex:
          root: inputs.InternalRange
          transformers:
          - operator: uniq
      ResolveIP:
        complex:
          root: inputs.ResolveIP
      UseReputationCommand:
        complex:
          root: inputs.UseReputationCommand
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich IP using one or more integrations.

        IP enrichment includes:
        * Resolve IP to Hostname (DNS)
        * Threat information
        * Separate internal and external addresses
        * IP reputation
        * For internal addresses, get host information
      id: 777ec369-d05d-4f8f-8c43-8068566e3ed0
      iscommand: false
      name: IP Enrichment - External - Generic v2
      playbookId: IP Enrichment - External - Generic v2
      type: playbook
      version: -1
    taskid: 777ec369-d05d-4f8f-8c43-8068566e3ed0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      IP:
        complex:
          root: inputs.IP
          transformers:
          - operator: uniq
      InternalRange:
        complex:
          root: inputs.InternalRange
          transformers:
          - operator: uniq
      ResolveIP:
        complex:
          root: inputs.ResolveIP
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich IP using one or more integrations.

        IP enrichment includes:
        * Resolve IP to Hostname (DNS)
        * Threat information
        * Separate internal and external addresses
        * IP reputation
        * For internal addresses, get host information
      id: 6d0d48a2-7a07-400b-8f98-9c832a56ff8f
      iscommand: false
      name: IP Enrichment - Internal - Generic v2
      playbookId: IP Enrichment - Internal - Generic v2
      type: playbook
      version: -1
    taskid: 6d0d48a2-7a07-400b-8f98-9c832a56ff8f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
