contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 98290833-da7b-4475-868e-54dbe065d82b
inputs: []
name: amir-new
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 234aa615-9083-41c2-8ef6-dab76abc07c5
      iscommand: false
      name: ""
      version: -1
    taskid: 234aa615-9083-41c2-8ef6-dab76abc07c5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "100"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: c7608b51-28d4-493c-81f0-5b0bd1523eda
      iscommand: false
      name: "100"
      script: Print
      type: regular
      version: -1
    taskid: c7608b51-28d4-493c-81f0-5b0bd1523eda
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 320
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "200"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 2c76f5c2-95fc-4c2e-8fad-c33f8c94c4d4
      iscommand: false
      name: "200"
      script: Print
      type: regular
      version: -1
    taskid: 2c76f5c2-95fc-4c2e-8fad-c33f8c94c4d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 605,
        "width": 400,
        "x": 440,
        "y": 50
      }
    }
  }
